### PR TITLE
Fix ring tokens sorting regression introduced in #3601

### LINKED ISSUE #3769: 1.7.0-rc0 querier incorrectly interpreting ring from 1.6.0 ingesters
**Describe the bug**
The symptom I noticed was queriers not fetching information from the ingesters that had it.
However it is easier to show on the `/ring` page:

1.6.0 querier returns:

Instance ID | Availability Zone | State | Address | Registered At | Last Heartbeat | Tokens | Ownership | Actions
-- | -- | -- | -- | -- | -- | -- | -- | --
ingester-7dfdbf869c-4hvdw |   | ACTIVE | 10.244.224.180:9095 | 2021-01-28 09:32:17 +0000 UTC | 2021-02-01 10:01:07 +0000 UTC | 512 | 10.158641894850563% | Forget
ingester-7dfdbf869c-6r4fn |   | ACTIVE | 10.244.221.144:9095 | 2021-01-28 07:50:03 +0000 UTC | 2021-02-01 10:01:08 +0000 UTC | 512 | 9.89586552835439% | Forget
ingester-7dfdbf869c-d4pr2 |   | ACTIVE | 10.244.220.95:9095 | 2021-01-28 09:12:31 +0000 UTC | 2021-02-01 10:01:06 +0000 UTC | 512 | 9.111226328907355% | Forget
ingester-7dfdbf869c-gp2ns |   | ACTIVE | 10.244.208.53:9095 | 2021-01-28 08:31:31 +0000 UTC | 2021-02-01 10:01:06 +0000 UTC | 512 | 9.926150415541175% | Forget
ingester-7dfdbf869c-j7d52 |   | ACTIVE | 10.244.229.179:9095 | 2021-01-28 07:29:40 +0000 UTC | 2021-02-01 10:01:05 +0000 UTC | 512 | 9.072090082120171% | Forget
ingester-7dfdbf869c-mlzwr |   | ACTIVE | 10.244.222.55:9095 | 2021-01-28 08:10:59 +0000 UTC | 2021-02-01 10:01:04 +0000 UTC | 512 | 10.601690716715924% | Forget
ingester-7dfdbf869c-q5896 |   | ACTIVE | 10.244.228.137:9095 | 2021-01-28 07:39:42 +0000 UTC | 2021-02-01 10:01:10 +0000 UTC | 512 | 9.671895324641815% | Forget
ingester-7dfdbf869c-r98dz |   | ACTIVE | 10.244.223.122:9095 | 2021-01-28 10:59:13 +0000 UTC | 2021-02-01 10:01:08 +0000 UTC | 512 | 10.563680811450743% | Forget
ingester-7dfdbf869c-rjxrp |   | ACTIVE | 10.244.209.190:9095 | 2021-01-28 08:43:02 +0000 UTC | 2021-02-01 10:01:07 +0000 UTC | 512 | 9.86297999272658% | Forget
ingester-7dfdbf869c-xgmg5 |   | ACTIVE | 10.244.225.13:9095 | 2021-01-28 07:57:09 +0000 UTC | 2021-02-01 10:01:09 +0000 UTC | 512 | 11.135778904691287% | Forget

1.7.0-rc0 querier returns:

Instance ID | Availability Zone | State | Address | Registered At | Last Heartbeat | Tokens | Ownership | Actions
-- | -- | -- | -- | -- | -- | -- | -- | --
ingester-7dfdbf869c-4hvdw |   | ACTIVE | 10.244.224.180:9095 | 2021-01-28 09:32:17 +0000 UTC | 2021-02-01 09:53:32 +0000 UTC | 512 | 0.3203722881899151% | Forget
ingester-7dfdbf869c-6r4fn |   | ACTIVE | 10.244.221.144:9095 | 2021-01-28 07:50:03 +0000 UTC | 2021-02-01 09:53:23 +0000 UTC | 512 | 0.12026363986550449% | Forget
ingester-7dfdbf869c-d4pr2 |   | ACTIVE | 10.244.220.95:9095 | 2021-01-28 09:12:31 +0000 UTC | 2021-02-01 09:53:36 +0000 UTC | 512 | 0.12366164012897332% | Forget
ingester-7dfdbf869c-gp2ns |   | ACTIVE | 10.244.208.53:9095 | 2021-01-28 08:31:31 +0000 UTC | 2021-02-01 09:53:36 +0000 UTC | 512 | 0.0832138350427183% | Forget
ingester-7dfdbf869c-j7d52 |   | ACTIVE | 10.244.229.179:9095 | 2021-01-28 07:29:40 +0000 UTC | 2021-02-01 09:53:35 +0000 UTC | 512 | 19.463768023872692% | Forget
ingester-7dfdbf869c-mlzwr |   | ACTIVE | 10.244.222.55:9095 | 2021-01-28 08:10:59 +0000 UTC | 2021-02-01 09:53:34 +0000 UTC | 512 | 19.719515675613543% | Forget
ingester-7dfdbf869c-q5896 |   | ACTIVE | 10.244.228.137:9095 | 2021-01-28 07:39:42 +0000 UTC | 2021-02-01 09:53:37 +0000 UTC | 512 | 20.038082408727632% | Forget
ingester-7dfdbf869c-r98dz |   | ACTIVE | 10.244.223.122:9095 | 2021-01-28 10:59:13 +0000 UTC | 2021-02-01 09:53:33 +0000 UTC | 512 | 20.86624107809417% | Forget
ingester-7dfdbf869c-rjxrp |   | ACTIVE | 10.244.209.190:9095 | 2021-01-28 08:43:02 +0000 UTC | 2021-02-01 09:53:32 +0000 UTC | 512 | 18.94527755653143% | Forget
ingester-7dfdbf869c-xgmg5 |   | ACTIVE | 10.244.225.13:9095 | 2021-01-28 07:57:09 +0000 UTC | 2021-02-01 09:53:34 +0000 UTC | 512 | 0.31960385393342094% | Forget

Note that the "Ownership" column shows all around 10% in the first case, while some at 20% and some near 0% in the second.

'Show Tokens' is identical in each case.

**Storage Engine**
- [ ] Blocks
- [x] Chunks

### PR DESCRIPTION
**Pull request by pracucci**
**What this PR does**:
I've introduced a regression in #3601 assuming that tokens are always sorted in the ring. Actually, recent versions of Cortex guarantee it but if your Cortex cluster has been created long time ago and tokens have been transferred from a leaving ingester to a joining one over and over they are still unsorted in the ring.

In this PR:
- Guarantee sorted tokens when a `JOINING` ingester claim tokems from a `LEAVING` one
- Guarantee sorted tokens when an ingester read tokens from file
- Rollback tokens sorting in `Desc.GetTokens()` and `Desc.getTokensByZone()` which was removed in #3601 (required to cover the time range during which ingesters of the new Cortex version are rolling out)
- No CHANGELOG because I expect this to be cherry picked in `release-1.7`

My plan is:
- Merge this PR
- Cherry pick the fix into `release-1.7` 
- Open another PR to remove the sorting from `Desc.GetTokens()` and `Desc.getTokensByZone()` adding a CHANGELOG entry to require upgrade to Cortex 1.7 before upgrading to future version Cortex 1.8

The performance impact for the sorting re-introduced in `Desc.GetTokens()` and `Desc.getTokensByZone()` is pretty low:

```
benchmark                                   old ns/op     new ns/op     delta
BenchmarkRing_ShuffleShard_512Tokens-12     399147        427036        +6.99%
BenchmarkRing_Get-12                        781           787           +0.77%
```

_`Ring.Get()` is not expected to be impacted, the little diff is just noise._

**Which issue(s) this PR fixes**:
Fixes #3769

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by bboreham** [comment]
After this change, are tokens sorted in disk file and in KV store?
That would be a good thing to ensure, because we could then remove sort-on-load after a couple of versions.

**Review by bboreham — APPROVED** [review]
Looks ok

**Comment by pracucci** [comment]
> After this change, are tokens sorted in disk file and in KV store?

Yes, they should (unless I'm missing anything).

> because we could then remove sort-on-load after a couple of versions

My idea (in the PR description) was to remove it from the next version and require to upgrade to Cortex 1.7 before 1.8. What do you think? It would allow us to immediately remove the sort-on-load from `master`.

**Review by pstibrany — APPROVED** [review]
LGTM.

(Nit: when posting benchmarks, please include full output from benchstat, including statistical significance, otherwise they are not saying much).

**Comment by pracucci** [comment]
🤞 Let's go and hope (even if hope is never a strategy)

**Pull request merged**
