### PR TITLE
Reduce distributor memory usage when error volume is high

### PR DESCRIPTION
**Pull request by damnever**
**What this PR does**:

Avoid nesting httpgrpcutil.WrapHTTPGrpcError.

image

This cluster has ~600 QPS, and ~400 of them are 2xx.
image

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by harry671003** [comment]
If possible, could you add a heap profile after this fix for comparison?

**Comment by danielblando** [comment]
Nice optimization.

One question on your graph.
After the "upgrade with fix", I do see an increase in CPU, was that a rollback our or scale down?

**Comment by damnever** [comment]
@harry671003 before the fix, our workload was OOM so it was easy to capture, today, our error rate is decreasing, the `httpgrpcutil.WrapHTTPGrpcError` is nearly invisible, so there is nothing interesting.

@danielblando yes, the distributor scaled down after the rollback, and the upgrade with the fix has the same replica count as before.

**Review by yeya24 — APPROVED** [review]
Thanks!

**Pull request merged**
