### PR TITLE
Fix typo in push-images script

### PR DESCRIPTION
**Pull request by aditya-konarde**
Correct `quey` to `quay`

Nothing Major :)

### CODE REVIEW

**Comment by bboreham** [comment]
Thanks!
Sadly we have a bot that requires a signed-off line in the git commit.

**Comment by tomwilkie** [comment]
ping @aditya-konarde can you add a DCO please?

**Comment by aditya-konarde** [comment]
@bboreham @tomwilkie no problem, just updated the PR. (Not sure if amend or another commit is the usual way to go here in this repo). Thanks for the pointer and apologies for the delay :)

**Comment by tomwilkie** [comment]
Thanks!  In this case amend was the right thing.

**Pull request merged**
