### PR TITLE
Bump golangci to v1.39.0

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták gliptak@gmail.com

**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by pstibrany** [comment]
Hello. I've built a new build-image with your change: `quay.io/cortexproject/build-image:bump-golangci-pr-4241-935bae54c`.

Please follow instructions at https://cortexmetrics.io/docs/contributing/how-to-update-the-build-image/ (step 1 and 2 are done) and update this PR with this new image. Thank you!

**Comment by gliptak** [comment]
@pstibrany thank you for pointing to the update process. Made the update

**Comment by pstibrany** [comment]
> @pstibrany thank you for pointing to the update process. Made the update

Thank you. There are now lint errors to be fixed.

Do you also want to enable `promlinter` (in file /.golangci.yml`) as discussed in https://github.com/cortexproject/cortex/issues/4171?

**Comment by gliptak** [comment]
@pstibrany I'm working to setup a build locally and target to correct lint errors. I propose to have `promlinter` as followup PR

**Comment by pstibrany** [comment]
> @pstibrany I'm working to setup a build locally and target to correct lint errors. I propose to have `promlinter` as followup PR

Thank you. Followup PR for promlinter sounds good.

**Comment by gliptak** [comment]
I'm failing `make lint` (running in `golang:1.16` Docker image)

```
# make lint

>>>> Entering build container: protos
make: Entering directory '/go/src/github.com/cortexproject/cortex'
make: *** No rule to make target 'protos'.  Stop.
make: Leaving directory '/go/src/github.com/cortexproject/cortex'
Command exited with non-zero status 2
0.01user 0.04system 0:00.82elapsed 7%CPU (0avgtext+0avgdata 64204maxresi
dent)k
0inputs+0outputs (0major+5293minor)pagefaults 0swaps
make: *** [Makefile:134: protos] Error 2
```

for reference I ran `apt install docker.io sudo time protobuf-compiler protobuf-c-compiler`

**Review by pracucci — COMMENTED** [review]
The lint is still failing. Could you take a look and fix `warning` too, please?
```
level=warning msg="[runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive."
level=warning msg="[runner/nolint] Found unknown linters in //nolint directives: golint ignore stutter warning"
pkg/util/validation/errors.go:14:6: type name will be used as validation.ValidationError by other packages, and that stutters; consider calling this Error (golint)
type ValidationError error // nolint: golint ignore stutter warning
```

Also, I've just merged #4244. Could you update the build-image tag in `Makefile` as well, please?

**Comment by gliptak** [comment]
```
level=warning msg="[runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive."
```

seems to be a larger update (in particular related to incorrect comments in the codebase)
https://github.com/golangci/golangci-lint/issues/1892

As for

```
level=warning msg="[runner/nolint] Found unknown linters in //nolint directives: golint ignore stutter warning"
pkg/util/validation/errors.go:14:6: type name will be used as validation.ValidationError by other packages, and that stutters; consider calling this Error (golint)
type ValidationError error // nolint: golint ignore stutter warning
```

I tried various formats without success. Related to https://github.com/golangci/golangci-lint/issues/1450

Might consider going to `1.139.0` first? Thoughts?

**Comment by pracucci** [comment]
> Might consider going to 1.139.0 first?

Sounds good to me. Would allow us to do it step-by-step.

**Comment by gliptak** [comment]
@pracucci please publish build-image

**Comment by pstibrany** [comment]
> @pracucci please publish build-image

Doing this right now.

**Comment by pstibrany** [comment]
New image: `quay.io/cortexproject/build-image:golangci-update-pr-4241-40550805d`

**Comment by pracucci** [comment]
@gliptak Could you take a look at the failing linter, please?

**Pull request closed without merging**
