### PR TITLE
Add limit for store gateway downloaded bytes

### PR DESCRIPTION
**Pull request by yeya24**
**What this PR does**:

Add the limit from https://github.com/thanos-io/thanos/pull/5801 to Cortex. This is a store gateway only limit that limits all data downloaded for each gRPC request to store gateway.

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by yeya24** [comment]
It is kind of tricky. How Store Gateway works is that based on the matchers user query requests, it will try to fetch postings either from cache or from S3.
Users can write very high cardinality matchers to match several GB postings but end up matching no or few series. In this case `max_fetched_data_bytes_per_query` won't help since it only considers series and chunks bytes that match the result.

I think this limit can cover some edge cases but I am also not sure if it is good to have that. As we don't have the visibility for that and it is enforced per gRPC request, not per query.

**Comment by harry671003** [comment]
> I think this limit can cover some edge cases but I am also not sure if it is good to have that. As we don't have the visibility for that and it is enforced per gRPC request, not per query.

We enforce the `max_fetched_data_bytes_per_query` at the query level. If the `max_downloaded_bytes_per_request` is set equal to the `max_fetched_data_bytes_per_query` limit, this can still be useful to protect store-gateways from OOM kills.

**Comment by alanprot** [comment]
LGTM!

In the future we may consider deprecating the other ones? Did it help to prevent OOM?

**Comment by yeya24** [comment]
> In the future we may consider deprecating the other ones? Did it help to prevent OOM?

What are the other ones you mentioned here? The series and chunk limit on store gateway?

**Review by alanprot — APPROVED** [review]

**Comment by yeya24** [comment]
Merging it now.

**Pull request merged**
