### PR TITLE
simpler S3 bucket validation

### PR DESCRIPTION
**Pull request by Dieterbe**
**What this PR does**:

tiny code simplification

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by pstibrany — APPROVED** [review]
Thanks!

**Review by jtlisi — APPROVED** [review]
LGTM

**Review by pracucci — COMMENTED** [review]
Well, technically correct, but don't think it's safer than the previous version. If future changes add other validations after validating `cfg.Backend` without noticing the change introduced in this PR, then we'll introduce a bug. I personally believe the current logic is more future proof.

**Comment by pstibrany** [comment]
Per Marco's objection, let's keep it as is.

**Pull request closed without merging**
