### PR TITLE
Track separate ingestion rates for API and Rules

### PR DESCRIPTION
**Pull request by leth**
Allow us to tell if a user is still sending samples, or if they just have some rules using `absent(...)`

### CODE REVIEW

**Comment by bboreham** [comment]
Is this backwards-compatible, i.e. can an old client push data to an ingester that is expecting the new format?

**Comment by leth** [comment]
> Is this backwards-compatible, i.e. can an old client push data to an ingester that is expecting the new format?

From what I understand about GRPC's compatibility strategy, it should default to 0 like golang, which would report as `API`.

**Comment by csmarchbanks** [comment]
As it stands I don't think this deploys cleanly. If you try to deploy the ingesters first, then the distributors and ruler will try to get the api rate from a field that is no longer written to. If you try to deploy the distributors first then they will try to read from the api/rule fields that do not exist yet. 

Perhaps make the ingester still return the total IngestionRate to remedy this?

**Comment by leth** [comment]
> As it stands I don't think this deploys cleanly. If you try to deploy the ingesters first, then the distributors and ruler will try to get the api rate from a field that is no longer written to. If you try to deploy the distributors first then they will try to read from the api/rule fields that do not exist yet.

If I'm understanding the gRPC docs correctly:

> When a message is parsed, if the encoded message does not contain a particular singular element, the corresponding field in the parsed object is set to the default value for that field.

Old distributors -> new Ingester: Distributor reads old field, which will should be initialised to zero because it was missing from the message
new distributors -> old ingester: Distributor reads new field, which will should be initialised to zero because it was missing

Everything should still work, but there will be a window where the rate is reported as zero until both are on the same version.

> Perhaps make the ingester still return the total IngestionRate to remedy this?

I guess it would make sense to still return the total rate, because one might not want to upgrade the ingesters immediately. I'll amend the PR!

**Pull request merged**
