### PR TITLE
Add GoJek to the list of users

### PR DESCRIPTION
**Pull request by gouthamve**
Added with permission from @achilles42 who runs the cortex cluster there. They use it to collect their telegraf and prometheus metrics.

### CODE REVIEW

**Comment by achilles42** [comment]
Thanks @gouthamve 👍

**Comment by weeco** [comment]
You can also add REWE Digital GmbH - rewe-digital.com to the list.

**Comment by gouthamve** [comment]
I've added it :)

**Comment by weeco** [comment]
@gouthamve Thank you, the 'd' in "digital" should be small though :P

**Pull request merged**
