### PR TITLE
Include stream option in the remote read

### LINKED ISSUE #2495: Update remote read to the new streaming interface.
@bwplotka introduced a new streaming remote read in Prometheus, we should add the same to Cortex for people who point Prometheus and Thanos at Cortex.

### PR DESCRIPTION
**Pull request by ethervoid**
**What this PR does**:

This PR includes the streamed option in the remote read API

**Which issue(s) this PR fixes**:
Fixes #2495 

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by ethervoid** [comment]
@tomwilkie Hi! This is my first draft on this issue. I'd love if you could take a look and let me know if I'm in the right path or maybe I should use more the Prometheus code instead of copy parts into Cortex. Thank you!

**Comment by bboreham** [comment]
Thanks for this PR; I see it is a draft so only took a quick look over.

I would expect code like `StreamChunkedReadResponses` to be used from Prometheus rather than copied in.  We already take a copy in the `vendor` directory.  If the function needs to change to work inside Cortex please make that clear, e.g. a comment saying `/* Copied from prometheus/foo/bar.go and modified to align flux capacitors */`

As you may know we have v1 ("chunks") and v2 ("blocks" or "tsdb") implementations of storage; since we have deprecated v1 now it is fine to implement streaming read responses only for v2 / tsdb implementation.

**Comment by ethervoid** [comment]
@bboreham Thank you for your answer! That was one of my main questions and now it's solved. I'll use the Prometheus code instead of creating my own :)

**Comment by ethervoid** [comment]
I'm still working on this one 🙏

**Comment by ethervoid** [comment]
Been inactive for a while, I'm planning to spend some Christmas time on this one

**Comment by Rahul-Bhardwaj2000** [comment]
Since this PR didnt get merged, just checking if this was ever implemented? Else I can work on this

**Comment by ethervoid** [comment]
Feel free to implement it :)

**Pull request closed without merging**
