### PR TITLE
Memcached: Fix comment typos

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does**:
Fix typos in comments in Memcached code.

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by pstibrany — APPROVED** [review]
Thank you.

**Comment by aknuds1** [comment]
@pstibrany I saw that the Memcached code inconsistently refers also to "memcache", especially in metric names. Should it be fixed up to consistently refer to "memcached" (e.g. in metrics)?

**Comment by pracucci** [comment]
> @pstibrany I saw that the Memcached code inconsistently refers also to "memcache", especially in metric names. Should it be fixed up to consistently refer to "memcached" (e.g. in metrics)?

Changing metrics is a bit of a pain for Cortex operators. I would live with the inconsistency and not do it.

**Review by pracucci — APPROVED** [review]
Thanks!

**Comment by pstibrany** [comment]
Feel free to do so, if you want. In that case, please make sure that CHANGELOG mentions all renamed metrics, and it would be nice to update metric names in https://github.com/grafana/cortex-jsonnet repository too. If these metrics are used by Loki or Tempo, it would be great to update their dashboards and alerts as well. If you decide it's not worth all the troubles, that's completely understandable.

**Comment by aknuds1** [comment]
> > @pstibrany I saw that the Memcached code inconsistently refers also to "memcache", especially in metric names. Should it be fixed up to consistently refer to "memcached" (e.g. in metrics)?
> 
> Changing metrics is a bit of a pain for Cortex operators. I would live with the inconsistency and not do it.

@pracucci OK, I figured the metric names might need to be kept :)

**Comment by aknuds1** [comment]
@pstibrany I decided to take @pracucci's advice.

**Pull request merged**
