### PR TITLE
Add cortex_ingester_tsdb_data_replay_duration_seconds metric

### LINKED ISSUE #5471: Metrics for tsdb startup time
**Is your feature request related to a problem? Please describe.**
Add some metrics to show the tsdb startup time.

**Describe the solution you'd like**
We can reuse the tsdb level metrics, such as `prometheus_tsdb_data_replay_duration_seconds` and `prometheus_tsdb_snapshot_replay_error_total`. Alternatively, we can also introduce new metrics at the cortex level specific to each tenant.

### PR DESCRIPTION
**Pull request by damnever**
**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #5471 

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by yeya24** [comment]
Hi @damnever, sorry for the late review. I think this change looks good and we can add the metric.
Would you mind fixing the conflicts? Thanks

**Comment by yeya24** [comment]
@damnever Can you please update the unit test as well? https://github.com/cortexproject/cortex/blob/master/pkg/ingester/metrics_test.go#L481

**Comment by damnever** [comment]
@yeya24 unit test updated

**Review by yeya24 — APPROVED** [review]
.

**Pull request merged**
