### PR TITLE
Add OTLP write handler benchmark

### PR DESCRIPTION
**Pull request by SungJin1212**
This PR adds a benchmark for the OTLP write handler.

The result is as follows:
```
BenchmarkOTLPWriteHandler
BenchmarkOTLPWriteHandler/json_with_no_compression
BenchmarkOTLPWriteHandler/json_with_no_compression-10         	   57388	     19514 ns/op	   21898 B/op	     355 allocs/op
BenchmarkOTLPWriteHandler/json_with_gzip
BenchmarkOTLPWriteHandler/json_with_gzip-10                   	   36260	     33121 ns/op	   68106 B/op	     365 allocs/op
BenchmarkOTLPWriteHandler/proto_with_no_compression
BenchmarkOTLPWriteHandler/proto_with_no_compression-10        	   77604	     15191 ns/op	   19700 B/op	     263 allocs/op
BenchmarkOTLPWriteHandler/proto_with_gzip
BenchmarkOTLPWriteHandler/proto_with_gzip-10                  	   49032	     24456 ns/op	   64703 B/op	     270 allocs/op
PASS
```

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by friedrichg — APPROVED** [review]
CI doesn't run this. I am curious what are the numbers you are getting. do you mind sharing as a comment?

**Comment by SungJin1212** [comment]
@CharlieTLe 
I have refactored the test code.

**Comment by SungJin1212** [comment]
@CharlieTLe 
Could you take a look when you have time?

**Review by alanprot — APPROVED** [review]
Thanks

**Review by CharlieTLe — APPROVED** [review]

**Comment by CharlieTLe** [comment]
I was also able to reproduce a similar benchmark

```
goos: darwin
goarch: arm64
pkg: github.com/cortexproject/cortex/pkg/util/push
cpu: Apple M1 Pro
BenchmarkOTLPWriteHandler
BenchmarkOTLPWriteHandler/json_with_no_compression
BenchmarkOTLPWriteHandler/json_with_no_compression-10         	   58062	     19842 ns/op	   21834 B/op	     353 allocs/op
BenchmarkOTLPWriteHandler/json_with_gzip
BenchmarkOTLPWriteHandler/json_with_gzip-10                   	   35395	     33751 ns/op	   68043 B/op	     363 allocs/op
BenchmarkOTLPWriteHandler/proto_with_no_compression
BenchmarkOTLPWriteHandler/proto_with_no_compression-10        	   75156	     15652 ns/op	   19636 B/op	     261 allocs/op
BenchmarkOTLPWriteHandler/proto_with_gzip
BenchmarkOTLPWriteHandler/proto_with_gzip-10                  	   46663	     26699 ns/op	   64640 B/op	     268 allocs/op
PASS
```

**Pull request merged**
