### PR TITLE
BREAKING fix(chunk/cache): Remove diskcache

### LINKED ISSUE #1336: Cortex does not compile for Windows
refer [issue](https://github.com/grafana/loki/issues/193)

### PR DESCRIPTION
**Pull request by sh0rez**
According to #1424, diskcache is not required anymore.
It is being removed, because it depends on UNIX specific features (unix.Mmap()),
making it impossible to compile Cortex and dependent projects on Windows.

**BREAKING**: Removes `store.index-cache-write.diskcache.*` flags

Fixes #1336 
Closes #1424

### CODE REVIEW

**Comment by sh0rez** [comment]
> @bboreham 
> Is it correct that `go.mod` and `vendor/modules.txt` change, but no files change under `vendor` ?

Yes, I have rechecked it by removing the entire vendor folder and running `go mod vendor`, it seems to be very sure about it.

**Comment by tomwilkie** [comment]
LGTM from me too.

**Comment by sh0rez** [comment]
@bboreham Merge?

**Comment by gouthamve** [comment]
LGTM!

**Pull request merged**
