### PR TITLE
code cleanup following staticcheck

### PR DESCRIPTION
**Pull request by beautytiger**

### CODE REVIEW

**Comment by bboreham** [comment]
Thanks for the PR!

Is this everything reported by staticcheck, or just part of it?

Would you like to have a go at including staticcheck in the CircleCI jobs?

**Comment by beautytiger** [comment]
It's only part of all the staticcheck, all of it may take some time.
Sure, it's my pleasure to add this feature to CI.
Do you have anything for reference, about how to add a CI job,or a ref pr?

**Comment by bboreham** [comment]
CI is controlled by this file: https://github.com/cortexproject/cortex/blob/master/.circleci/config.yml

There is [documentation](https://circleci.com/docs/2.0/configuration-reference/) on the CircleCI site.

You could look at changes like cc141c3f0671f9c406e5ef2c0c2b32a0676c62c9

**Comment by beautytiger** [comment]
Got it, let me dig into it.

**Pull request merged**
