### PR TITLE
Add opstrace to adopters list

### PR DESCRIPTION
**Pull request by gouthamve**
@jgehrcke I'll soon share the screenshot of how the website will look!

### CODE REVIEW

**Comment by gouthamve** [comment]
image

**Review by pracucci — APPROVED** [review]
🎉  We also have `ADOPTERS.md`: do you mind adding it there as well?

**Comment by gouthamve** [comment]
I already did :)

**Comment by jgehrcke** [comment]
Approved! :rocket: 
Thank you!

**Pull request merged**
