### PR TITLE
Update prometheus to v2.30.0

### PR DESCRIPTION
**Pull request by simonswine**
**What this PR does**:

Update prometheus to v2.30.0

**Which issue(s) this PR fixes**:

This supersedes #4437 **edit: corrected number**

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by pracucci — APPROVED** [review]
LGTM, thanks!

**Comment by bboreham** [comment]
> This supersedes #4473

That one is merged, did you mean a different number?

Note a couple of merge conflicts, also we like to call out key changes in the CHANGELOG (if any).

**Comment by bboreham** [comment]
Changes I can see in the Prometheus code:
- added `present_over_time` function
- optional TSDB head snapshot on shutdown (possibly not exposed by Cortex?)
- optimisations to speed up TSDB and use less memory

**Comment by bboreham** [comment]
OK I'll do the changelog.

**Comment by simonswine** [comment]
> > This supersedes #4473

@bboreham sorry, that was the wrong number #4437 is correct. Thanks for sorting out the CHANGELOG.md

**Pull request closed without merging**
