### PR TITLE
[Querier] Add day range limit for LabelNames and LabelValues

### PR DESCRIPTION
**Pull request by afhassan**
**What this PR does**:
Check day range limit in LabelNames and LabelValues. Return query too long error if `MaxQueryLength` limit is exceeded.

### CODE REVIEW

**Review by yeya24 — COMMENTED** [review]
Looks good. Can we add a unit test?

**Review by yeya24 — APPROVED** [review]
LGTM!

**Comment by alanprot** [comment]
Seems this broke the query with no parameters as we default to min time

https://github.com/prometheus/prometheus/blob/d9a54284f5bcf5d82b2552a00fc476669c3634d5/web/api/v1/api.go#L670-L672

**Comment by yeya24** [comment]
Unfortunately I think it breaks things as by default label names and label values can have no start and end parameters specified.

So by default all those APIs without time range parameters will be denied. I think the behavior is not wrong but at current stage the behavior change breaks existing use cases.

So we need to find another way around. Maybe fallback to a smaller time range and add a warning

**Pull request merged**
