### PR TITLE
Set appropriate headers in /services endpoint.

### PR DESCRIPTION
**Pull request by jmcarp**
Signed-off-by: Josh Carp <jm.carp@gmail.com>

**What this PR does**:

I noticed that the /services endpoint response renders as plain text in some situations. The /services endpoint also sets Content-Type to text/plain when returning json. I see that we always set the Content-type to text/plain in the handler, which I'm proposing we drop unless we need it for some reason.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by bboreham — APPROVED** [review]
Thanks!
Looks like this was an omission from #2673.
Could you reword the CHANGELOG entry so that an administrator can read through the list and get some idea whether they need this fix?  It should be understandable without having to refer to the source code.
E.g. "/services html was previously declared to be plain text"

**Comment by jmcarp** [comment]
Happy new year @bboreham! I fixed the changelog. Let me know if I missed anything else.

**Review by alvinlin123 — APPROVED** [review]

**Comment by alvinlin123** [comment]
@jmcarp  thanks for the contribution! Would you be able to fix the conflicts and I'll get this PR merges :-)

**Comment by alvinlin123** [comment]
Alright, I was afraid that if I make edit through web UI for change log DCO would complain, but looks like it didn't :-) Sorry for the false alarm @jmcarp

**Pull request merged**
