### PR TITLE
Add ability to support strict JSON unmarshal for `limits`

### PR DESCRIPTION
**Pull request by kavirajk**
**What this PR does**:
Main problem is currently we cannot strict unmarshal JSON for `Limits` struct using [json.DisallowUnknownFields()](https://golang.org/pkg/encoding/json/#Decoder.DisallowUnknownFields). Because custom `UnmarshalJSON` uses simple `json.Unmarshal()` function. (is it intentional?)

This PR Adds ability to support strict JSON unmarshal for `limits` struct

This is the default behaviour for YAML now.
```
	in := `{"unknown_fields": 100}`
	l := validation.Limits{}

	fmt.Println(yaml.UnmarshalStrict([]byte(in), &l))

	// yaml: unmarshal errors:
	// line 1: field unknown_fields not found in type validation.plain
```

This PR adds same behaviour if unmarshalled from JSON input as well.

**Which issue(s) this PR fixes**:
Fixes NA

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by stevesg — COMMENTED** [review]
Looks fine assuming this is the behavior we want, but some points to consider:

- Does mean that we lose forward compatibility? i.e. a "newer" configuration file (with unknown fields) cannot be parsed by an older version of Cortex. Whatever is producing the limits/overrides files, must be perfectly in sync with the Cortex version. This may be an acceptable trade-off.
- ~~Correct me if I'm wrong, but does this now mean that JSON parsing does not accept unknown fields, whilst the YAML parsing *does*? This perhaps is a little odd, I would expect both to have the same behavior.~~
- ~~Also [unrelated curiosity], given [runtime_config.go:65](https://github.com/cortexproje1ct/cortex/blob/8bdf5b1f77d9915aedb3e3e60d8a29d80061a911/pkg/cortex/runtime_config.go#L65), I wonder if it was actually intentional for the YAML parsing to accept unknown fields...~~

**Comment by pstibrany** [comment]
> * Correct me if I'm wrong, but does this now mean that JSON parsing does not accept unknown fields, whilst the YAML parsing _does_? This perhaps is a little odd, I would expect both to have the same behavior.

As you point out in your next point, we already use strict parsing for YAML runtime config (which includes overrides), so this PR actually unifies both YAML and JSON parsing to strict.

Cortex itself doesn't use JSON parsing for limits, as far as I know.

**Comment by stevesg** [comment]
Ah my mistake, I misread the `UnmarshalYAML` function. OK then it makes sense that both are strict.

**Review by pstibrany — APPROVED** [review]

**Comment by kavirajk** [comment]
Thanks @stevesg @pstibrany!. Yes that's right this PR unifies both JSON and YAML strict with unknown fields!

**Review by stevesg — APPROVED** [review]

**Review by pracucci — APPROVED** [review]
LGTM!

**Review by bboreham — APPROVED** [review]
Great job!

**Pull request merged**
