### PR TITLE
Count the number of rate-limited samples in distributor_samples_in_total

### PR DESCRIPTION
**Pull request by damnever**
**What this PR does**:
Currently, there are no metrics that include rate-limited samples. I am considering counting the number of rate-limited samples in distributor_samples_in_total. Alternatively, we could add a separate metric.

**Which issue(s) this PR fixes**:

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by yeya24** [comment]
@danielblando @wenxu1024 Can you guys help review this pr?

**Comment by yeya24** [comment]
Hi @damnever, for your usecase, do you need to differentiate how many samples are `rate-limited`?

It is probably fine to add those samples to be counted in `distributor_samples_in_total` as it says to count `The total number of samples that have come in to the distributor, including rejected or deduped samples`.

**Comment by wenxu1024** [comment]
LGTM

**Comment by damnever** [comment]
@yeya24 `distributor_samples_in_total` works fine for me as it gives me a sense of the total number of samples.

**Review by danielblando — APPROVED** [review]
LGTM.

**Review by yeya24 — APPROVED** [review]

**Pull request merged**
