### PR TITLE
log with system time zone

### LINKED ISSUE #1304: log with system time zone
For [code](https://github.com/cortexproject/cortex/blob/master/pkg/util/log.go#L72), it always use UTC time zone, is it possible to use system time zone, it would be better to read for users from any time zone.

### PR DESCRIPTION
**Pull request by daixiang0**
Fix #1304 

Signed-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Comment by bboreham** [comment]
Thanks for the PR.

When I have to support servers in multiple timezones, I prefer UTC.
I guess it could be an option.

**Comment by daixiang0** [comment]
Do you mean add a func with this option?

**Comment by bboreham** [comment]
I meant a command-line option. 

If you look around, how do you see this done in other server software?

**Comment by daixiang0** [comment]
They do not use UTC but system time zone, for softwares which call `pkg/util/log`, do not get how to switch to system time zone.

**Comment by daixiang0** [comment]
@bboreham any input? Do you have any idea about switch UTC to system time zone when call `pkg/util/log`.

**Comment by bboreham** [comment]
I am starting to wonder if this makes no practical difference to me, since we run Cortex inside containers and containers default to UTC. 

For yourself, how do you propose to run Cortex such that timezone information is available?  Outside of containers?

What do other maintainers think?  @tomwilkie @khaines @gouthamve

**Comment by daixiang0** [comment]
In my case, since my time zone is not UTC, the log time is useless for me, so i want to mount /etc/localtime then i can get time in my time zone. But Cortex uses UTC as default and have no option to do it now.

**Comment by khaines** [comment]
My local timezone is not UTC, but all of our machines & containers deployed around the world have UTC set as their TZ. 

I guess I'm feeling that this sort of TZ conversion should be done outside of cortex. The log processing tools we use allow for viewing logs in local time and it handles that conversion at display time vs recording time.

**Comment by daixiang0** [comment]
@khaines could you give me an example, i do not know how to use local time when call `corex/pkg/util/log`.

**Comment by khaines** [comment]
@daixiang0 What I was saying is that I log everything in UTC, though I do not live in the UTC zone; so there is no code example for cortex that I can give you.

I use external tools such as fluentd/logstash/Loki/Elasticsearch to process log files. These tools do the TZ conversion for me, so when I'm reading logs the timestamps appear in my local TZ.

**Pull request closed without merging**
