### PR TITLE
Adding AlertManager SNS Receiver Implementation

### PR DESCRIPTION
**Pull request by alanprot**
**What this PR does**:
* Updating Prometheus AlertManager dependency
   * https://github.com/prometheus/alertmanager/pull/2615
   * https://github.com/prometheus/alertmanager/pull/2648
* Adding Support to SNS Receiver on AlertManager

**Which issue(s) this PR fixes**:

**Checklist**
- [NA] Tests updated
- [X] Documentation added
- [X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by treid314 — APPROVED** [review]
Thanks! LGTM, Can you changelog entry to be with the other features to stick to format?

**Comment by alanprot** [comment]
Done and rebased! :D

**Comment by jeromeinsf** [comment]
Can you please also review this PR @alolita @Aneurysm9?

**Review by bboreham — APPROVED** [review]
Thanks!  Couple of asks before merge:

Please fix the conflict (formatting in CHANGELOG), and also call out the update to Prometheus alertmanager code in the PR description.

Check what else gets picked up by the update - e.g. were there any major bug-fixes or deprecations in alertmanager between the old and new commits.

**Comment by alanprot** [comment]
Thanks @bboreham 
I just rebased the branch and added the change set in the PR. We are bringing just 2 PRs.

**Review by bboreham — APPROVED** [review]
Thanks!

**Review by treid314 — APPROVED** [review]
Thanks for adding the changes in Alertmanager to the PR!

**Review by pracucci — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
