### PR TITLE
return ErrStorageObjectNotFound when object requested for download is not found in Azure blob storage

### PR DESCRIPTION
**Pull request by sandeepsukhani**
**What this PR does**:
When `GetObject` method is called on any of the object stores and the object is not there in the storage then we return `ErrStorageObjectNotFound` which is not the case for azure blob storage. This PR makes the required changes to make it consistent with other stores.

I have copied some of the code from thanos for the checks https://github.com/thanos-io/thanos/blob/main/pkg/objstore/azure/azure.go#L179

### CODE REVIEW

**Comment by pstibrany** [comment]
I am wondering if it would be possible to use [`ServiceCode `](https://github.com/cortexproject/cortex/blob/e0f7db5c6440280a46ac53b1bafd629b3072751f/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_storage_error.go#L28) from `StorageError` type and check against [`ServiceCodeBlobNotFound`](https://github.com/cortexproject/cortex/blob/e0f7db5c6440280a46ac53b1bafd629b3072751f/vendor/github.com/Azure/azure-storage-blob-go/azblob/service_codes_blob.go#L14).

**Comment by sandeepsukhani** [comment]
> ServiceCodeBlobNotFound

Makes sense. I have updated the code.
Thanks!

**Review by pracucci — APPROVED** [review]
👍

**Review by gouthamve — APPROVED** [review]
LGTM

**Pull request merged**
