### PR TITLE
 Fixing ambiguous double negative for ingesters

### PR DESCRIPTION
**Pull request by warmfusion**
(Signed version of https://github.com/cortexproject/cortex/pull/3749) 

Fixing ambiguous terminology from double negatives;

"doesn't receive neither this and that". As neither is Not Either, this could suggest that it accepts both concurrently as 'either' binds the two operations together, but it really wants to be suggesting that these operations are mutually exclusive.

Not sure this is the clearest explanation I've ever created on a ticket, but i hope it makes sense.

Reading this section made my eye twitch which may just be my own problem so if you think the current version is valid that's fine by me. I'm not an expert in English grammar :-)

**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [x] Tests updated
- [x] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by bboreham — APPROVED** [review]
Thanks!

**Comment by bboreham** [comment]
Please review the [DCO requirement](https://github.com/cortexproject/cortex/pull/4554/checks?check_run_id=4183957343)

**Review by pracucci — APPROVED** [review]

**Comment by warmfusion** [comment]
So i ran the sign-off stuff again, if it doesn't work this time., close the ticket forever.

I don't mind DCO rules etc, but honestly this is a pain for just a two word docs change.

**Review by aknuds1 — APPROVED** [review]

**Comment by aknuds1** [comment]
Does anyone know how come the DCO check fails? Agree it's a pain :/

**Comment by bboreham** [comment]
There are 4 commits in this PR, one of which is not signed-off.
I imagine you just want one commit.
Should be able to do `git rebase -i origin/master`, then put `squash` on every line, then edit the message to what you want with the signed-off line at the end.  Then `git push origin +patch-1`.

Or if you prefer I can do this for you - GitHub gives me as a maintainer permission to write to your branch.

**Comment by warmfusion** [comment]
yeah - squash doens't help cos i did a merge up from master after 9 months so there are 470~ other commits.

Nevermind.

**Pull request closed without merging**
