### PR TITLE
Release 1.1

### PR DESCRIPTION
**Pull request by pstibrany**
**What this PR does**: Release 1.1 preparation. I did initial changelog review.

Based on master 1ea1d190bf0919cf51b02ba1ef09310cddf93365.

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by pstibrany** [comment]
> IIUC, you first make these changes in your own branch and open a PR against the release branch (release-1.1 here).

Hmm, should I start over then? :)

**Comment by codesome** [comment]
> Hmm, should I start over then? :)

I think so :) Also https://github.com/cortexproject/cortex/issues/2578#issuecomment-626730265, you will have to clear these new commits from `release-1.1` too and have commits only via a PR to that branch. (Do other maintainers agree with me? :) )

**Comment by pstibrany** [comment]
OK. I will close this one, push changes to my own branch and create PR to merge it into release-1.1 branch. Thanks @codesome!

**Comment by pstibrany** [comment]
Moved to https://github.com/cortexproject/cortex/pull/2579

**Pull request closed without merging**
