### PR TITLE
date was wrong; fixed

### PR DESCRIPTION
**Pull request by asloan7**

### CODE REVIEW

**Comment by csmarchbanks** [comment]
Thanks! Look like you need to sign the DCO though.

**Comment by asloan7** [comment]
I did the change through the web browser, did the DCO after (rats), now cloned https://github.com/asloan7/cortex/tree/patch-1, did git commit --amend --signoff and trying to do 
 git push --force-with-lease origin patch-1 but says: 
error: failed to push some refs to https://github.com/asloan7/cortex.git

**Comment by csmarchbanks** [comment]
You could try just a `git push --force` rather than `--force-with-lease`

**Comment by asloan7** [comment]
git push --force origin patch-1
error: src refspec patch-1 does not match any
error: failed to push some refs to 'https://github.com/asloan7/cortex.git

**Comment by csmarchbanks** [comment]
Weird, that error suggests the `patch-1` branch does not exist, which it definitely does on the remote. Since `git push --force` worked, are you on the `patch-1` branch in your local repo?

**Comment by asloan7** [comment]
git checkout -b patch-1
Switched to a new branch 'patch-1'

git push --force
fatal: The current branch patch-1 has no upstream branch.

git push --set-upstream origin patch-1
To https://github.com/asloan7/cortex.git
 ! [rejected]          patch-1 -> patch-1 (non-fast-forward)
error: failed to push some refs to 'https://github.com/asloan7/cortex.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Maybe I should close the PR and try from scratch

**Comment by csmarchbanks** [comment]
> Maybe I should close the PR and try from scratch

That might be easiest :)

By doing `git checkout -b patch-1` you made a new local branch called `patch-1` that is not the same as your upstream patch. To fix this the following steps should work:
```
$ git rebase origin/patch-1
$ git commit --amend --signoff
$ git push --force-with-lease --set-upstream origin patch-1
```
This assume you are on the `patch-1` branch.

Hope that helps/works!

**Comment by asloan7** [comment]
Yea, and now "This branch is 1 commit ahead, 3 commits behind cortexproject:master"

**Pull request merged**
