### PR TITLE
update caching_bucket according to thanos changes

### PR DESCRIPTION
**Pull request by akanshat**
Signed-off-by: akanshat <akanshat1999@gmail.com>

**What this PR does**:
Updates caching_bucket in cortex with the new changes introduced with [groupcache](https://github.com/thanos-io/thanos/pull/4818) in package `store` and `storecache` in Thanos.
**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by akanshat** [comment]
@GiedriusS I wanted to update cortex to point to Thanos with our refactored packages. I ran `go get github.com/thanos-io/thanos@main` but after running `go mod vendor` I seem to have changed 400 files. Is this correct? 😵‍💫

**Review by GiedriusS — APPROVED** [review]
LGTM. The changes come from the vendored Go modules. Not sure why Cortex still does this :thinking:

**Comment by bwplotka** [comment]
👍🏽

**Comment by bwplotka** [comment]
Any chances for review on this?

**Comment by bwplotka** [comment]
It is making us to use fork of Cortex

**Comment by alanprot** [comment]
@GiedriusS Can your rebase this?

**Comment by akanshat** [comment]
Sorry for looking at this so late, I will rebase this over the weekend.

**Comment by akanshat** [comment]
@alanprot rebased this 😄

**Comment by alanprot** [comment]
Build failed! =/

**Comment by alanprot** [comment]
Hi..

Im trying to update thanos to main on https://github.com/cortexproject/cortex/pull/4780

**Comment by alanprot** [comment]
I will close this as Thanos was updated on https://github.com/cortexproject/cortex/pull/4780

**Pull request closed without merging**
