### PR TITLE
Update Thanos to latest and use label matchers in LabelValues call.

### PR DESCRIPTION
**Pull request by pstibrany**
**What this PR does**: This PR updates Thanos to latest main to bring in https://github.com/thanos-io/thanos/pull/4107. This PR also passes matchers to `LabelValuesRequest` sent to store gateways.

**Checklist**
- [na] Tests updated
- [na] Documentation added
- [na] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by simonswine — APPROVED** [review]
LGTM

**Comment by pstibrany** [comment]
Related to #3658 (only label values support added here. Label names is missing support in Prometheus `storage.LabelQuerier` interface still.

**Review by pracucci — COMMENTED** [review]
Oh that was easy! LGTM!

Thanos changes LGTM (they basically only contain your PR).

Side note: would be great to have at least a test on this, but we can do it in a follow-up PR once the Label Names API will be addressed too.

**Review by pracucci — APPROVED** [review]

**Comment by pstibrany** [comment]
> Side note: would be great to have at least a test on this, but we can do it in a follow-up PR once the Label Names API will be addressed too.

Added testing of matchers into existing integration tests. At the moment Label Names API is not important for work I'm doing, so I will let that one be for now.

**Comment by pracucci** [comment]
> Added testing of matchers into existing integration tests.

LGTM, thanks!

**Pull request merged**
