### PR TITLE
integration: Moved image references to single place.

### PR DESCRIPTION
**Pull request by pstibrany**
**What this PR does**: This trivial PR moves all docker image references used in integration tests to single place, to keep them together and remove repeated comment.

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

/cc @bwplotka

### CODE REVIEW

**Comment by pstibrany** [comment]
> If we consider this package as a library, I think we might want something more flexible than globals ):
> 
> I know it's more work, but I would vote for parameter instead, so Cortex can have it's own globals and Thanos can choose to use different version etc... WDYT? 🤔

What about making a global map with images?

```
var Images map[string]string = {
    "memcached": "memcached:1.6.1",
    "minio": "minio/minio:RELEASE.2019-12-30T05-45-39Z",
    ...
}
```

This way, we would keep image references at one place, and they can still by updated by client code via `init` method? Passing image name as a parameter would affect lot of code, for little benefit.

**Comment by bwplotka** [comment]
I mean for now it's hardcoded anyway, so global map or var is better than nothings (: Would do for now (: In terms of map I think just global `vars` would do for now.

Once we will need parameters we will think what to do (:

**Comment by pstibrany** [comment]
> Once we will need parameters we will think what to do (:

I'd like to introduce functional parameters here. So that we can write things like: `e2e.NewHTTPService("name", Image("..."), ReadinessProbe(...))` etc.

That would also allow us to introduce new options without touching half of the tests each time.

**Comment by bwplotka** [comment]
In this case maybe struct would do better, no?

**Comment by pstibrany** [comment]
> In this case maybe struct would do better, no?

I agree structs would work too. How would be better though?

**Comment by bwplotka** [comment]
Because it's always better to refer to things by variable name that is typed than random string (:

**Comment by pstibrany** [comment]
> Because it's always better to refer to things by variable name that is typed and hast to exists on compile time than random string (:

Using functional parameters are not random strings, but functions that have to have correct signature. So they are checked at compile time. Similar to go-kit logger, or many other examples. (https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis)

**Comment by bwplotka** [comment]
Yea, I know what functional arguments works, this will work perfectly for sure.

But this does not looks like functional argument, so that's why I was confused.

```
var Images = map[string]string{
    "memcached": "memcached:1.6.1",
    "minio": "minio/minio:RELEASE.2019-12-30T05-45-39Z",
    ...
}
```

As long as this map does not exists, and some functional args are used it would be perfect yes (:

**Comment by pstibrany** [comment]
> Yea, I know what functional arguments works, this will work perfectly for sure.
> 
> But this does not looks like functional argument, so that's why I was confused.
> 
> ```
> var Images = map[string]string{
>     "memcached": "memcached:1.6.1",
>     "minio": "minio/minio:RELEASE.2019-12-30T05-45-39Z",
>     ...
> }
> ```
> 
> As long as this map does not exists, and some functional args are used it would be perfect yes (:

Ah, sorry, I misunderstood you. I've changed opinion on this, and used `var` instead of `const`. That way they can still be overwritten, but also compile-time checked.

(I wasn't going to use raw strings like that anyway, but would provide key constants.)

**Comment by pstibrany** [comment]
> > Yea, I know what functional arguments works, this will work perfectly for sure.
> > But this does not looks like functional argument, so that's why I was confused.

Functional arguments suggestion was proposal for further changes in this library, but not in this PR. It was reaction to your comment:

> Once we will need parameters we will think what to do (:

**Pull request merged**
