### PR TITLE
Do not backoff when max retries is 0.

### PR DESCRIPTION
**Pull request by jeschkies**
**What this PR does**:
The backoff logic would keep retrying if the maximum number of retries was set to 0.

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by bboreham** [comment]
Infinite retries is what this comment says you should expect:
https://github.com/cortexproject/cortex/blob/4405f9c339779b5861f5755bd867ee7bac4f4fa9/pkg/util/backoff.go#L15

**Comment by jeschkies** [comment]
Ah. Then the documentation should reflect this. It's a little counter intuitive. -1 would have been nice but that's most probably a breaking change.

**Comment by bboreham** [comment]
Agreed it should be in the docstring.  I think it is really the number of _tries_, i.e. if you set `MaxRetries` to 1 it tries once.

**Comment by jeschkies** [comment]
Not a bug.

**Pull request closed without merging**
