### PR TITLE
Reduce lock contention on series creation and del

### PR DESCRIPTION
**Pull request by gouthamve**
`cortex_ingester_memory_series_removed_total` might never be created if a user's series' never expire. Also, this reduces the lock contention around the metrics.

### CODE REVIEW

**Comment by tomwilkie** [comment]
LGTM!

**Comment by bboreham** [comment]
Maybe explain a bit how this works, for people who haven't studied Prometheus' client-go internals?
You are caching access to a "sub-counter", something like that?

**Comment by bboreham** [comment]
Is this worth doing in similar cases, e.g. `dynamoQueryRetryCount.WithLabelValues("BatchWrite")` ?

**Comment by gouthamve** [comment]
Yes. When we do `WithLabelValues` a lock is taken to lookup the right counter. We should cache is as much as possible, specially in cases where there are tons of lookups.

Further, when we just call `WithLabelValues()` without an `Inc()`, the counter is created for those values and is set to `0`.

**Pull request merged**
