### PR TITLE
Reintroduce util/runtimeconfig package

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does**:
Reintroduce util/runtimeconfig package, in place of dskit/runtimeconfig.

**Which issue(s) this PR fixes**:

**Checklist**
- [x] Tests updated
- [na] Documentation added
- [na] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by pracucci — APPROVED** [review]
LGTM

**Review by pstibrany — APPROVED** [review]

**Comment by pstibrany** [comment]
Can you please rebase this PR?

**Comment by aknuds1** [comment]
> Can you please rebase this PR?

@pstibrany will do.

**Comment by pstibrany** [comment]
Thank you.

**Pull request merged**
