### PR TITLE
Periodically clear out limiters in the distributor.

### LINKED ISSUE #1095: Distributor ingest limit never auto-update due to caching
https://github.com/cortexproject/cortex/blob/9cf5767ecfdbe962d6e96b9d293969cceec012db/pkg/distributor/distributor.go#L309-L315

Here we are caching the limiter for every user. Which means if the limit is updated via the config file it never reflects for the user and a restart is needed.

### PR DESCRIPTION
**Pull request by gouthamve**
Periodically clear out any cached ingestion rate limiters, such that updates to the overrides YAML take ~5mins to apply.

Fixes #1095

### CODE REVIEW

**Comment by tomwilkie** [comment]
This could do with a better description @gouthamve - something like "Periodically clear out any cached ingestion rate limiters, such that updates to the overrides YAML take ~5mins to apply."

Why 5mins?  

Also, put "fixes #1095" in the description.

**Comment by bboreham** [comment]
Why create new limiters rather than call `SetLimit()` on the existing ones?

**Comment by tomwilkie** [comment]
> Why create new limiters rather than call SetLimit() on the existing ones?

Clearing the limit map also acts as a crude was of GCing limiter for users that have gone away.

**Comment by tomwilkie** [comment]
LGTM

**Comment by bboreham** [comment]
There's also an unfortunate interaction with the burst limit - each time you create a Limiter you reset the burst allowance, so if someone sets the burst limit very high then you will never hit the real limit.

**Comment by tomwilkie** [comment]
>  if someone sets the burst limit very high and you reset every five minutes then they will never hit the real limit.

Is that a real world concern?  I like this as it kills two birds (GC and change limit), but we can always forget about the GCing - we don't do it right now!

**Pull request merged**
