### PR TITLE
Add index stats info to bucket index

### PR DESCRIPTION
**Pull request by yeya24**
**What this PR does**:

We added Index Stats info to the `meta.json` file and use that to estimate series and chunk size. However, when store gateway uses bucket index, it won't actually download `meta.json` file from object store. It will generate `meta.json` file from the information provided by bucket index.

This pr adds additional fields `series_max_size ` and `chunk_max_size` to bucket index per block to help address this issue. The change is also backward compatible from what I tested.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [X] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by friedrichg — APPROVED** [review]
LGTM

**Comment by yeya24** [comment]
The issue of current implementation is that, for old blocks in the bucket index, we don't update `series_max_size` and `chunk_max_size` fields because bucket index updater just copies what we have from the old bucket index.
Only those new blocks that don't appear in bucket index will be added with those fields

**Comment by alanprot** [comment]
> The issue of current implementation is that, for old blocks in the bucket index, we don't update series_max_size and chunk_max_size fields because bucket index updater just copies what we have from the old bucket index.
Only those new blocks that don't appear in bucket index will be added with those fields

This should be fine for this PR?

**Comment by yeya24** [comment]
> This should be fine for this PR?

Yeah I think it should be fine. It is another story of migration, which can be done separately.

**Pull request merged**
