### PR TITLE
Reintroduce pkg/util/middleware, in place of dskit/middleware

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does**:
Reintroduce pkg/util/middleware, in place of dskit/middleware

**Which issue(s) this PR fixes**:

**Checklist**
- [x] Tests updated
- [na] Documentation added
- [na] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by pracucci — APPROVED** [review]
Thanks|

**Comment by pstibrany** [comment]
This needs a rebase now :(

**Comment by aknuds1** [comment]
> This needs a rebase now :(

@pstibrany done!

**Comment by pstibrany** [comment]
> > This needs a rebase now :(
> @pstibrany done!

Thank you, enabled auto-merge.

**Comment by pstibrany** [comment]
Oh no, there is another conflict not :-(

**Pull request merged**
