### PR TITLE
Updated gocql dependency

### PR DESCRIPTION
**Pull request by VineethReddy02**
Signed-off-by: vineeth <vineethpothulapati@outlook.com>

@pracucci

### CODE REVIEW

**Comment by pracucci** [comment]
@joshmue Given you opened the issue https://github.com/cortexproject/cortex/issues/2007, may you build Cortex with this PR merged into and test it against Azure CosmosDB to see if it fixes your issue, please?

**Comment by pracucci** [comment]
@VineethReddy02 Could you check if any breaking (or worth to note) change has been introduced in `gocql` by this PR, please?

**Comment by joshmue** [comment]
> @joshmue Given you opened the issue #2007, may you build Cortex with this PR merged into and test it against Azure CosmosDB to see if it fixes your issue, please?

Of course! I will setup a testing build/environment and confirm it ASAP.

**Comment by VineethReddy02** [comment]
@pracucci 
I tested this changes by running single instance cortex with cassandra. 

1. I was able to notice all the tables in cassandra and also all the data was shown in dashboards as usual.
2. It's very starnge gocql is not maintianing any CHANGELOG.md or RELEASE.MD. So I manually had high level look on merged PR's. I didn't notice any chnages that might effect cortex in best of my knowledge.

**Comment by pracucci** [comment]
Thanks @VineethReddy02. Let's wait for the tests done by @joshmue too.

**Comment by joshmue** [comment]
@pracucci @VineethReddy02 

Unfortunately, the update was not sufficient. The error message is now:

```
msg="error initializing cortex" err="gocql: unable to create session: unable to discover protocol version: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config
```

Which suggests that `ServerName` should be set here (inside of the embedded tls.Config):
https://github.com/cortexproject/cortex/blob/ab3e8360fe30150a516448e4c3bae596dc4d8a17/pkg/chunk/cassandra/storage_client.go#L81

According to my understanding, this is only applicable to single-endpoint setups using TLS and domain names, as there is only a single `gocql.SslOptions` (containing `tls.Config`) passed into `gocql.ClusterConfig`.

So a little bit of code handling the multiple cases may be required.
These cases may include:
- single domain name with TLS and host verification (compare https://github.com/gocql/gocql/blob/95d072f1b5bbc604ce10f41ce1c914578592ed00/conn.go#L91)
- multiple IP's without TLS (compare https://github.com/gocql/gocql/blob/95d072f1b5bbc604ce10f41ce1c914578592ed00/cluster.go#L157)
- multiple IP's without host verification
- ...

Of course, this would be out of scope for this PR. If you want, I can take a look into this in a seperate PR.

**Comment by pracucci** [comment]
@VineethReddy02 Have you had any chance to test it?

**Comment by VineethReddy02** [comment]
@pracucci I never experienced this issue. But if @joshmue can help me in re-producing with env setup and in writing the fix. I can take this up. Else, I am totally fine with @joshmue taking this up.

**Comment by joshmue** [comment]
I shrunk the example single process config to this:

```yaml
ingester:
  lifecycler:
    join_after: 0
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

storage:
  cassandra:
    timeout: 10s
    addresses: <Azure CosmosDB endpoint>
    port: 10350
    keyspace: cortex
    SSL: true
    host_verification: true
    auth: true
    username: <...>
    password: <...>
schema:
  configs:
  - from: 2019-07-29
    store: cassandra
    object_store: cassandra
    schema: v10
    index:
      prefix: index_
      period: 168h
    chunks:
      prefix: chunk_
      period: 168h
```

Toggling `storage.cassandra.host_verification` to `false` prevents this error.

**Comment by joshmue** [comment]
@VineethReddy02 Is this information sufficient?

**Comment by VineethReddy02** [comment]
@joshmue I don't think I can replicate the env with azure credentials by creating cosmos db instance. I think @joshmue should take this change in another PR. If it's okay we should merge gocql updation in this PR as I did required testing with local env. If not we can close this PR and take gocql updation in another PR with changes required to support the cosmos DB.
WDYT @pracucci

**Comment by pracucci** [comment]
I'm OK merging this PR to update gocql, but I've edited the PR description to remove the reference to the issue #2007 cause it's not going to be fixed by this PR. Please @VineethReddy02 fix the conflict.

**Comment by joshmue** [comment]
> @joshmue I don't think I can replicate the env with azure credentials by creating cosmos db instance. I think @joshmue should take this change in another PR.

For reference: I opened this draft PR: #2109

**Pull request merged**
