### PR TITLE
Update golang to 1.14.9 in build-image

### PR DESCRIPTION
**Pull request by simonswine**
**What this PR does**:

Update the base image in the build-image to the latest golang 1.14 release.

Changelog:

https://github.com/golang/go/issues?q=milestone%3AGo1.14.9+label%3ACherryPickApproved+
https://github.com/golang/go/issues?q=milestone%3AGo1.14.8+label%3ACherryPickApproved+
https://github.com/golang/go/issues?q=milestone%3AGo1.14.7+label%3ACherryPickApproved+
https://github.com/golang/go/issues?q=milestone%3AGo1.14.6+label%3ACherryPickApproved+
https://github.com/golang/go/issues?q=milestone%3AGo1.14.5+label%3ACherryPickApproved+

**Checklist**
- [] Tests updated
- [] Documentation added
- [] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by roidelapluie** [comment]
Shouldn't we use 1.15.2?

**Comment by simonswine** [comment]
I am not too sure what cortex usually does, I just thought ahead of the next releases it would be good to update Go to the latest patch version.

**Comment by pstibrany** [comment]
I think we could merge this PR for Cortex 1.4, and once that release branch is cut (this week), we can update to Go 1.15.

**Comment by pracucci** [comment]
> I think we could merge this PR for Cortex 1.4, and once that release branch is cut (this week), we can update to Go 1.15.

I agree on this. I will pick up this PR from here, since a maintainer is required (the doc for the whole process is here: https://cortexmetrics.io/docs/contributing/how-to-upgrade-golang-version/).

**Review by pstibrany — APPROVED** [review]

**Pull request merged**
