### PR TITLE
chore: Updating Prometheus to v0.40.7 and Thanos to 3327c510076a

### PR DESCRIPTION
**Pull request by alanprot**
Signed-off-by: Alan Protasio <approtas@amazon.com>

**What this PR does**:
Updating Prometheus to v0.40.7.

This prometheus version contains the native histograms but we are not supporting it for now.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [NA] Tests updated
- [NA] Documentation added
- [NA] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by alanprot** [comment]
Ok..

Seems we will need to update AM on Thanos:

```
# github.com/thanos-io/thanos/pkg/httpconfig
vendor/github.com/thanos-io/thanos/pkg/httpconfig/http.go:176:73: not enough arguments in call to config_util.NewTLSRoundTripper
	have (*tls.Config, string, func(tlsConfig *tls.Config) ("net/http".RoundTripper, error))
	want (*tls.Config, string, string, string, func(*tls.Config) ("net/http".RoundTripper, error))
make: *** [cmd/cortex/cortex] Error 2
```

**Comment by yeya24** [comment]
> Seems we will need to update AM on Thanos:

How is that related to AM? Isn't it `prometheus/common`?

**Comment by alanprot** [comment]
Yeah.. but the new AM that brought the new Common.

And the old AM is failing cause: 

```
~/w/c/cortex (update-prometheus ⚡→↩) make BUILD_IN_CONTAINER=false
Building cmd/cortex/cortex for amd64
# github.com/prometheus/alertmanager/cluster
vendor/github.com/prometheus/alertmanager/cluster/tls_config.go:26:23: undefined: web.TLSStruct
```

So i needed to update AM that brought the new Common that broke thanos :)

**Comment by songjiayang** [comment]
nice job.

**Review by yeya24 — APPROVED** [review]
Thanks! I think we can update Prometheus to v2.41.0 directly but we can do that in next pr.

**Pull request merged**
