### PR TITLE
Add Alan Protasio as maintainer

### PR DESCRIPTION
**Pull request by alvinlin123**
Vote result: https://groups.google.com/g/cortex-team/c/7HHNN4YPucA

Welcome @alanprot !

(Let me know if you want a different email address - I took that one from your public GitHub profile)

### CODE REVIEW

**Review by alanprot — APPROVED** [review]

**Comment by alanprot** [comment]
Thanks @alvinlin123  😄

**Comment by alvinlin123** [comment]
Per https://cortexmetrics.io/docs/contributing/how-to-add-a-maintainer/ here are the action items:

* Submit a PR to add the new member to MAINTAINERS (it's this PR)
* Invite to GitHub organization
* Invite to cortex-team group
* Invite to Quay.io repository
* Invite to Docker Hub organization
* Invite to CNCF cncf-cortex-maintainers mailing list (via CNCF Service Desk)
* Add to the Google Analytics property used for the website statistics 
  * No idea how to do this.

**Review by pracucci — APPROVED** [review]

**Comment by pracucci** [comment]
>  Invite to cortex-team group
> Ok doesn't look like I have power to add people to the Google group, will need help.

@alvinlin123 I gave you ownership privileges (sorry it wasn't done before). I've also invited @alanprot to 2 mailing lists: `cortex-vendors-announce@googlegroups.com` and `cortex-team@googlegroups.com`

**Comment by pracucci** [comment]
>  Add to the Google Analytics property used for the website statistics
> No idea how to do this.

I added both of you as administrators. You should have received an email.

**Comment by pracucci** [comment]
>  Invite to Docker Hub organization

Need help with this?

**Comment by alvinlin123** [comment]
> > Invite to Docker Hub organization
> 
> Need help with this?

Yes, if you can. Last time when Bryan was trying to add me, it says limit is hit. But maybe things changed.

**Comment by alvinlin123** [comment]
Submitted a service desk request to add Alan: https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1069

**Comment by alvinlin123** [comment]
will merge this, as it seems like in order for Alan to be in cncf mailing list, Alan needs to be added to the maintainer file in Cortex.

**Pull request merged**
