### PR TITLE
Fixing README guide links

### PR DESCRIPTION
**Pull request by dannykopping**
**What this PR does**:
Fixes documentation links

**Which issue(s) this PR fixes**:
N/A

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by codesome — APPROVED** [review]

**Review by pstibrany — APPROVED** [review]
Thank you!

**Comment by pstibrany** [comment]
Can you please fix DCO?

**Comment by dannykopping** [comment]
@pstibrany sure thing, done :+1:

**Review by pracucci — APPROVED** [review]
Thanks a lot!

**Pull request merged**
