### PR TITLE
Add more documentation on AM templates

### PR DESCRIPTION
**Pull request by jpdstan**
Signed-off-by: Stan Kwong <stanley.kwong@robinhood.com>

**What this PR does**:
Adds more documentation on how to import template files into your Alertmanager configuration.

**Which issue(s) this PR fixes**:
Fixes https://github.com/cortexproject/cortex/issues/3194

**Checklist**
- [x] Tests updated
- [x] Documentation added
- [documentation changes don't seem to fix into any of these?] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by jpdstan** [comment]
Weird, i wonder why the PR isn't auto-merging with your approval 🤔

**Review by pracucci — APPROVED** [review]
LGTM

**Review by pstibrany — APPROVED** [review]

**Comment by pstibrany** [comment]
Thank you!

**Comment by gotjosh** [comment]
> Weird, i wonder why the PR isn't auto-merging with your approval 🤔

As much as I'm honoured by your comment, I'm not a Cortex maintainer. My approvals show up differently in Github.

**Pull request merged**
