### PR TITLE
[Vote] Daniel Blando (danielblando) as new Cortex maintainer

### PR DESCRIPTION
**Pull request by friedrichg**
I would like to call for a vote to add @danielblando as Cortex maintainer.

Daniel has been very active in contributing to Cortex since 2021. Here is [a list of Daniels's contributions](https://github.com/cortexproject/cortex/issues?q=author%3Adanielblando). There is no doubt Daniel will keep contributing in the years to come

Per [existing change in maintainership governance rule](https://cortexmetrics.io/docs/contributing/governance/#changes-in-maintainership), 2/3 majority votes are required for the changes to pass.

Please cast your yes/no vote as comment in this PR, I will leave the vote open for 14 days (including weekends) or until all maintainer voted; whichever comes first.

### CODE REVIEW

**Comment by alvinlin123** [comment]
+1

**Comment by CharlieTLe** [comment]
Yes

**Comment by alanprot** [comment]
+1

**Comment by yeya24** [comment]
+1

**Comment by friedrichg** [comment]
+1

**Review by CharlieTLe — APPROVED** [review]

**Pull request merged**
