### PR TITLE
Update Alertmanager to latest master (f686ff3be2bf).

### LINKED ISSUE #4234: Upgrade alertmanager to 0.22.1+
Updating alertmanager adds new functionality such as negative matches/timebased routing....
Full Notes: https://github.com/prometheus/alertmanager/releases/tag/v0.22.0

### PR DESCRIPTION
**Pull request by pstibrany**
**What this PR does**: This PR updates alertmanager to latest master (https://github.com/prometheus/alertmanager/commit/f686ff3be2bf519fb271414f2d8401e0a6c32f24).

**Which issue(s) this PR fixes**:
Fixes #4234

**Checklist**
- [na] Tests updated
- [na] Documentation added
- [na] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by pstibrany** [comment]
Integration tests currently failing due to bug in JSON-marshalling of URL wrapper. PRs with the fix: 
- https://github.com/prometheus/common/pull/303
- https://github.com/prometheus/alertmanager/pull/2607

**Review by stevesg — APPROVED** [review]
Looks good assuming the upstream fixes are merged.

**Review by pracucci — APPROVED** [review]
I checked the changes in alertmanager and common: LGTM (modulo the URL marshalling issue you've found).

A nit, non blocking: while looking at the code I've noticed a TODO at `integration/e2ecortex/client.go:211`. Can we fix it?

**Comment by pstibrany** [comment]
> I checked the changes in alertmanager and common: LGTM (modulo the URL marshalling issue you've found).
> 
> A nit, non blocking: while looking at the code I've noticed a TODO at `integration/e2ecortex/client.go:211`. Can we fix it?

I don't see what struct to use here. Alertmanager v1 api uses inline struct to send the response: https://github.com/cortexproject/cortex/blob/5e496f428302a195a68cc287d97641561dbe0afd/vendor/github.com/prometheus/alertmanager/api/v1/api.go#L171

**Comment by pracucci** [comment]
> > I checked the changes in alertmanager and common: LGTM (modulo the URL marshalling issue you've found).
> > A nit, non blocking: while looking at the code I've noticed a TODO at `integration/e2ecortex/client.go:211`. Can we fix it?
> 
> I don't see what struct to use here. Alertmanager v1 api uses inline struct to send the response:
> 
> https://github.com/cortexproject/cortex/blob/5e496f428302a195a68cc287d97641561dbe0afd/vendor/github.com/prometheus/alertmanager/api/v1/api.go#L171

I think it was added by @jtlisi: do you remember it?

_In any case, this is definitely not a blocker, so please merge this PR as soon as ready._

**Comment by bboreham** [comment]
Since this added features and deprecated others, it really needed a CHANGELOG comment.
From the issue: "Updating alertmanager adds new functionality such as negative matches/timebased routing...."
`match`, `match_re` are deprecated.

**Comment by bboreham** [comment]
The new feature side was added to CHANGELOG in #4325.

**Pull request merged**
