### PR TITLE
Update thanos version to 62038110b1bc

### PR DESCRIPTION
**Pull request by harry671003**
**What this PR does**:
Updating thanos dependency to https://github.com/thanos-io/thanos/commit/62038110b1bc47b1324b06a0f7d91c8bce680e5e.

The only major change that will impact cortex is:
- https://github.com/thanos-io/thanos/pull/7814

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by yeya24** [comment]
For the lint issue, let's upgrade the dependency to v0.3.4, similar to https://github.com/prometheus/prometheus/pull/15166?

**Comment by yeya24** [comment]
@SungJin1212 https://github.com/cortexproject/cortex/actions/runs/11585758704/job/32255315640?pr=6294
This may related to the new disable chunk trimming change

**Comment by harry671003** [comment]
Looks like the test is flaky.

**Comment by SungJin1212** [comment]
@harry671003 
Yes, it seems that.
I get the intermittent error even if two Cortexs use the same image, `quay.io/cortexproject/cortex:v1.18.0`. It seems to be a bug in the test code.

**Review by yeya24 — APPROVED** [review]
LGTM

**Pull request merged**
