### PR TITLE
Fixing grammar mistakes & consistent spelling for query frontend

### PR DESCRIPTION
**Pull request by rolanderdei**
**What this PR does**:
Fixes mistake in the documentation.
Most of them are grammar mistakes + creating consistent spelling for query frontend in the documentation.

_Extension of PR: 4438._

### CODE REVIEW

**Comment by bboreham** [comment]
Linter is indicating you need to re-generate some files; probably `make doc`.

**Comment by bboreham** [comment]
Now CI seems to be in an indeterminate state.  Perhaps pushing an empty commit will un-stick it.

**Review by bboreham — APPROVED** [review]
Approving the content, but it has to pass CI before merging.

**Comment by rolanderdei** [comment]
It looks like it needs a maintainer.

**Comment by alanprot** [comment]
Seems that both files (template and md) needs to be included in the PR in order to make the lint happy :D

**Comment by friedrichg** [comment]
This PR is so old, it needs a rebase. Maybe we can pick up the good parts in other PRs.

**Pull request closed without merging**
