### PR TITLE
Remove `dynamo` as a valid storage option

### PR DESCRIPTION
**Pull request by rsteneteg**
Signed-off-by: Roger Steneteg <rsteneteg@ea.com>

### CODE REVIEW

**Comment by rsteneteg** [comment]
This allows the usage of `store: dynamo` which otherwise would work for the NewIndexClient, but would fail for table-manager when calling the NewTableClient.

**Comment by bboreham** [comment]
Another way to be consistent would be to remove "dynamo", if it never actually worked.
"aws-dynamo" is identical, as far as I can see.
@tomwilkie do you recall why "dynamo" was half-added in #1120 ?

**Comment by gouthamve** [comment]
:+1: to removing `dynamo` if `aws-dynamo` is actually the same thing. @rsteneteg Would you be able to do the change?

**Comment by rsteneteg** [comment]
@gouthamve @bboreham My only concern with removing `dynamo` is that it may break users current configuration.

**Comment by gouthamve** [comment]
We could make a clear note in the changelog? This is a relatively minor
change (easy to fix) and something that is super noticable (rollouts will
fail).

**Comment by rsteneteg** [comment]
For chunks the ObjectClient accepts `aws` and `s3` for S3 storage, since there is no `aws-s3` and for bigtable the option is called just `bigtable` not `gcp-bigtable`, so I think it makes more sense to keep the `dynamo` option over removing it.

**Comment by bboreham** [comment]
The case you are trying to fix is where someone has configured Querier or Ingester with `dynamo` and Tablemanager with `aws-dynamo`, and you want to let them say `dynamo` everywhere ?

I just don't like adding options which aren't necessary.

**Comment by rsteneteg** [comment]
ok I have have updated the PR to remove the `dynamo` option.

**Comment by gouthamve** [comment]
@rsteneteg Could you update the changelog with this change? It might break some users and is best called out.

**Comment by rsteneteg** [comment]
Ok, have updated the change log as well now, the reason I did not add it before is that the breaking change where `dynamo` was no longer supported by table manager had already been done.

**Pull request merged**
