### PR TITLE
Querier: streamline tracing spans

### LINKED ISSUE #3913: internalQuerier tracing spans are disconnected from parent
**Describe the bug**
image

Container image `cortexproject/cortex:master-5e496f4`

**Expected behavior**
That span should have a parent; looking at the `url` and `method` tags it should be one of these:
image

**Storage Engine**
- [x] Blocks
- [ ] Chunks

### PR DESCRIPTION
**Pull request by bboreham**
**What this PR does**:

Remove `internalQuerier` trace handler: `nethttp.MiddlewareFunc()` starts a new top-level trace, but we already have tracing middleware from `Server.HTTPServer`.

One doubt: I'm not sure what happens in single-binary mode.  I could not follow this comment: https://github.com/cortexproject/cortex/blob/ebef1e1a08e1f650d011e11aaa512ffca5c6b727/pkg/cortex/modules.go#L327-L329

I cannot see how this code affects processed using the external HTTP Server, because it only impacts what happens to requests routed via the query-frontend worker.

**Which issue(s) this PR fixes**:
Fixes #3913 

**Checklist**
- NA Tests updated
- NA Documentation added
- [x] `CHANGELOG.md` updated

### CODE REVIEW

**Review by pracucci — COMMENTED** [review]
@jtlisi I think you've been the last one working on it. Could you review it, please?

**Comment by pracucci** [comment]
I just did a quick test with the single-binary and I confirm this PR breaks tracing there. I've run the single-binary with:
```
./development/tsdb-blocks-storage-s3-single-binary/compose-up.sh
```

What I get in master:
Screenshot 2021-03-09 at 18 42 21

What I get with this PR:
Screenshot 2021-03-09 at 18 41 05

**Comment by jtlisi** [comment]
> @jtlisi I think you've been the last one working on it. Could you review it, please?

Sorry I took so long to get to this. It had been a while since I had worked on this and needed to re-familiarize myself with why this was needed.

1. We inject the `retry` parent trace span into the request as an HTTP header [here in pkg/frontend/v1/frontend.go](https://github.com/cortexproject/cortex/blob/161f103ed5baaf2d1518a01d277c1d48959823ca/pkg/frontend/v1/frontend.go#L155-L162)
    ```go
    // RoundTripGRPC round trips a proto (instead of a HTTP request).
    func (f *Frontend) RoundTripGRPC(ctx context.Context, req *httpgrpc.HTTPRequest) (*httpgrpc.HTTPResponse, error) {
        // Propagate trace context in gRPC too - this will be ignored if using HTTP.
        tracer, span := opentracing.GlobalTracer(), opentracing.SpanFromContext(ctx)
        if tracer != nil && span != nil {
            carrier := (*grpcutil.HttpgrpcHeadersCarrier)(req)
            err := tracer.Inject(span.Context(), opentracing.HTTPHeaders, carrier)
            if err != nil {
                return nil, err
            }
        }
    ```
1. We then send the [HTTPGRPC request](https://github.com/weaveworks/common/blob/master/httpgrpc/httpgrpc.pb.go), using a GRPC streaming service. This means there isn't a context scoped to the request because the `httpgrpc.Request` does not persist the context.
1. The only place the span now exists is the HTTP header of the request. In microservices mode, the request is passed to the weaveworks/common servers router and the tracing middleware will extract the Span Headers and inject them into the context. However, in single-binary mode, we use a separate router, specifically the one returned by the function edited in this PR. If tracing middleware is not applied to this router, then the span HTTP headers are never extracted. We could only apply the tracing middleware in single-binary mode. However, I don't think there is a downside in having an additional operation to keep traces between the two models consistent.

**Comment by bboreham** [comment]
I re-introduced the tracing middleware in the single-binary path.
Still don't follow the comments there.

**Review by pracucci — APPROVED** [review]
I re-tested it and looks working fine both in microservices mode (with and without query-scheduler) and single-binary mode.

**Pull request merged**
