### PR TITLE
Cherrypick commits for 1.16.1

### LINKED ISSUE #5881: Release v1.16.1
**Describe the bug**
Include:

**To Reproduce**
1. Start Cortex (SHA or version)
2. Perform Operations(Read/Write/Others)

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Additional Context**

### PR DESCRIPTION
**Pull request by yeya24**
**What this PR does**:

Cherrypick commits for 1.16.1.

**Which issue(s) this PR fixes**:
Fixes #5881 

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by friedrichg — APPROVED** [review]

**Comment by yeya24** [comment]
Linter failed...
Yeah indeed we upgraded go version to 1.21.9 so we need to fix linter as well here

**Comment by friedrichg** [comment]
you need the lint fixes from https://github.com/cortexproject/cortex/pull/5711 here

**Comment by yeya24** [comment]
@friedrichg Linter passed... Let's see if it is good to go this time.

**Review by friedrichg — APPROVED** [review]

**Comment by friedrichg** [comment]
I should have not squashed the commits :(

**Pull request merged**
