### PR TITLE
add curl to support container probes with mTLS

### LINKED ISSUE #4427: container probes fail when Cortex mutual TLS is enabled
**Describe the bug**
I followed the [instructions here ](https://cortexmetrics.io/docs/guides/tls/) to enable mTLS in Cortex. 
I deployed Cortex from the latest [helm chart](https://github.com/cortexproject/cortex-helm-chart).

The outcome is pods are being terminated because the [startup probe](https://github.com/cortexproject/cortex-helm-chart/blob/master/values.yaml#L444) must present a client TLS when making a [readiness probe](https://cortexmetrics.io/docs/api/#readiness-probe) request.

Fortunatelly the helm chart [provides the ability](https://github.com/cortexproject/cortex-helm-chart/blob/master/values.yaml#L444) to overwrite the container probes with a command instead of http-get. 
Unfortunatelly the Cortex image is [missing curl](https://github.com/cortexproject/cortex/blob/master/cmd/cortex/Dockerfile#L2) to implement a probe alternative such as:

`curl -s --cert /srv/certs/cert.pem --key /srv/certs/key.pem --cacert /srv/certs/ca.crt --resolve server.common.name:8080:127.0.0.1 https://server.common.name:8080/ready`

I suspect adding _curl_ to the Cortex base image would help. Is there anything else I could use instead ?

### PR DESCRIPTION
**Pull request by danfromtitan**
**What this PR does**:
Adds curl to the container image.

**Which issue(s) this PR fixes**:
Fixes #4427

**Checklist**
- [-] Tests updated
- [-] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by bboreham** [comment]
I prefer not to do this; see https://github.com/cortexproject/cortex/issues/4427#issuecomment-972707651

**Comment by danfromtitan** [comment]
I replied with more details in https://github.com/cortexproject/cortex/issues/4427#issuecomment-973058351
Until kubernetes adds support for client TLS http-get probes, I don't see any other option to probe Cortex containers with mTLS enabled.

**Comment by ShuzZzle** [comment]
> I replied with more details in [#4427 (comment)](https://github.com/cortexproject/cortex/issues/4427#issuecomment-973058351) Until kubernetes adds support for client TLS http-get probes, I don't see any other option to probe Cortex containers with mTLS enabled.

I concurr with this. I don't think there is another way currently unfortunately since kubelet always skips cert validation when using `https`

**Comment by danfromtitan** [comment]
still needed

**Pull request closed without merging**
