### PR TITLE
chore: update documentation to use new API paths

### PR DESCRIPTION
**Pull request by jtlisi**
**What this PR does**:

- Update all documentation to use the `/api/v1/push` and `/prometheus` routes where relevant
- Example Nginx configs have been updated to support both endpoints

### CODE REVIEW

**Review by pracucci — APPROVED** [review]
Thanks for working on it! I agree we should move the doc and examples to new (non-legacy) endpoints.

What do you think about changing the endpoints used by integration tests too? Look for `/api/prom` in `integration/`: there are multiple references there.

**Comment by jtlisi** [comment]
> What do you think about changing the endpoints used by integration tests too? Look for /api/prom in integration/: there are multiple references there.

I'm onboard with changing the references there as well.

**Comment by pracucci** [comment]
Doh! Need to fix the backward compatibility test flags.

**Comment by jtlisi** [comment]
> Doh! Need to fix the backward compatibility test flags.

Mind if I revert to the previous commit and take on the integration tests in a separate PR?

**Comment by pracucci** [comment]
> > Doh! Need to fix the backward compatibility test flags.
> 
> Mind if I revert to the previous commit and take on the integration tests in a separate PR?

Sure, I don't mind.

**Pull request merged**
