### PR TITLE
Add a Code of Conduct referencing the CNCF Code of Conduct

### PR DESCRIPTION
**Pull request by csmarchbanks**
Shamelessly copied the format from other CNCF projects

Signed-off-by: Chris Marchbanks <csmarchbanks@gmail.com>

### CODE REVIEW

**Comment by gouthamve** [comment]
👍

**Comment by dholbach** [comment]
I don't have review rights, but :+1: for adding it! :-)

**Comment by juliusv** [comment]
:+1:

**Comment by cboggs** [comment]
:+1:

**Comment by tomwilkie** [comment]
I don’t have any comments on the CoC itself, but should we copy it in instead of referencing it? That was modifications will also be tracked and voted on here.

**Comment by csmarchbanks** [comment]
Seems like an extra thing to remember to do/keep track of, so I would slightly prefer referencing it. All the other CNCF projects seem to be referencing it as well.

**Pull request merged**
