### PR TITLE
[WIP] Remove userStatesMtx

### LINKED ISSUE #662: questions over userStatesMtx
Exhibit 1:
```
func (i *Ingester) query(ctx context.Context, from, through model.Time, matchers []*labels.Matcher) (model.Matrix, error) {
	i.queries.Inc()

	i.userStatesMtx.RLock()
	defer i.userStatesMtx.RUnlock()
	state, err := i.userStates.getOrCreate(ctx)
```

In what sense is this a _Read_ lock if we can _Create_ a user state inside it?
And why do we hold this lock (over all user states) for the duration of the query over one?
There are five other `RLock` calls which are very similar.

Exhibit 2:
```
// TransferChunks receives all the chunks from another ingester.
func (i *Ingester) TransferChunks(stream client.Ingester_TransferChunksServer) error {
[...]
	i.userStatesMtx.Lock()
	defer i.userStatesMtx.Unlock()

	if err := i.ChangeState(ring.ACTIVE); err != nil {
		return err
	}
	i.userStates = userStates

	return nil
```

This is the only place a write-lock is taken on `userStatesMtx`, and only for as long as it takes to CAS the state change.

Since there is a lock `mtx` inside `userStates` protecting its data, I suspect that `userStatesMtx` is left-over from some earlier implementation that needed it.

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #662.  This bugs me every time I read that code.

### CODE REVIEW

**Comment by rade** [comment]
AFAIK, golang pointer assignment is not guaranteed to be atomic.

**Comment by rade** [comment]
There are pointer operations in sync/atomic that could replace the mutex.

**Comment by bboreham** [comment]
OK, it's plausible that's what it's for, but if that were the case it shouldn't lock round the CAS too.

**Comment by bboreham** [comment]
actually that probably is intentional, but could be fixed by doing the update to `userStates` before `ChangeState()`

**Comment by bboreham** [comment]
But why is this pointer write happening anyway?  Why not just write the newly-received chunks into the existing `userStates`?  What are we protecting against?

**Comment by tomwilkie** [comment]
> But why is this pointer write happening anyway? Why not just write the newly-received chunks into the existing userStates? What are we protecting against?

I believe I was protecting against incoming writes creating new series/chunks, but the ingester state should prevent this itself.

**Comment by tomwilkie** [comment]
You could add a `swap` method to userStates that use the mtx in userstates to swap out the underlying map.

**Comment by tomwilkie** [comment]
Do you think we should close this PR?

**Comment by tomwilkie** [comment]
> Do you think we should close this PR?

I'm gonna say yes now.

**Pull request closed without merging**
