### PR TITLE
Update Thanos to latest master.

### PR DESCRIPTION
**Pull request by pstibrany**
**What this PR does**: This PR updates Thanos dependency to [latest master](https://github.com/thanos-io/thanos/commits/bb1662a1d13c). Main reason for update is to get https://github.com/thanos-io/thanos/pull/3261 in.

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by jtlisi — APPROVED** [review]
LGTM

**Review by pracucci — COMMENTED** [review]
@pstibrany This Thanos fix https://github.com/thanos-io/thanos/pull/3279 is a blocker for the upgrade. Could you keep it monitored, please?

**Comment by pstibrany** [comment]
> @pstibrany This Thanos fix [thanos-io/thanos#3279](https://github.com/thanos-io/thanos/pull/3279) is a blocker for the upgrade. Could you keep it monitored, please?

From what I understand, that only affects Receive part of Thanos, that we don't use.

**Comment by pracucci** [comment]
@pstibrany I'm going to close this PR in favour of #3363. If turns out #3363 can't be merged, we can reopen this PR anytime.

**Pull request closed without merging**
