### PR TITLE
Upgrade Prometheus for a patch release

### PR DESCRIPTION
**Pull request by codesome**
**What this PR does**:

Upgrade Prometheus in release-1.4 to https://github.com/prometheus/prometheus/tree/for-cortex-1-4-1 which is https://github.com/prometheus/prometheus/commit/c8062622063179bff4eed36df0bf81be3890902b on top of Prometheus already in the release.

cc @pracucci 

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by codesome** [comment]
Vendor update is massive, that is mostly because with changes in Prometheus, Cortex does not require vendoring all the service discovery files that it does not use. (same reason for https://github.com/cortexproject/cortex/pull/3231/)

**Comment by codesome** [comment]
Looking at the lint and build errors, looks like we need to upgrade some other components too. That does not sound like a patch release then.

**Comment by codesome** [comment]
Tried upgrading exactly upto https://github.com/prometheus/prometheus/commit/c8062622063179bff4eed36df0bf81be3890902b, same errors.

**Comment by roidelapluie** [comment]
> Looking at the lint and build errors, looks like we need to upgrade some other components too. That does not sound like a patch release then.

Prometheus HTTP client now has the ability to disable HTTP2 because of issues in the go HTTP2 client, hence the extra bool.

**Comment by codesome** [comment]
Yeah, which calls for alertmanager and Thanos upgrades

**Comment by roidelapluie** [comment]
You could cherry pick the commit you want on a branch of prometheus/prometheus and vendor that.

**Comment by codesome** [comment]
> You could cherry pick the commit you want on a branch of prometheus/prometheus and vendor that.

Right! @pracucci is that something we are ok to do?

**Comment by pracucci** [comment]
> > You could cherry pick the commit you want on a branch of prometheus/prometheus and vendor that.
> 
> Right! @pracucci is that something we are ok to do?

Yes, I think would be a better approach.

**Comment by codesome** [comment]
Cool! I will do it on Monday

**Comment by codesome** [comment]
@pracucci I have upgraded the Prometheus with cherry-pick now, should be a no brainer merge now

**Review by csmarchbanks — APPROVED** [review]
:+1:

**Review by pstibrany — APPROVED** [review]

**Review by jtlisi — APPROVED** [review]
LGTM

**Comment by codesome** [comment]
@pracucci can we close this since we are going to have a v1.5.0?

**Comment by pracucci** [comment]
> @pracucci can we close this since we are going to have a v1.5.0?

Agree. Closing because 1.5.0 stable release is close.

**Pull request closed without merging**
