### PR TITLE
Add BenchmarkChunkQueryableFromTar

### PR DESCRIPTION
**Pull request by codesome**
`BenchmarkChunkQueryableFromTar` is same as `TestChunkTar` in `pkg/querier/chunk_tar_test.go`. This benchmark would come handy in investigating a query offline.

### CODE REVIEW

**Comment by bboreham** [comment]
Can you factor out the common code?

**Comment by codesome** [comment]
Done

**Comment by bboreham** [comment]
What is the reason the remaining code is different between the benchmark and the test?
Looks like a limit and a timeout.

**Comment by codesome** [comment]
Yes, I was not sure if I should alter those limits (samples and timeout) for `TestChunkTar`. And I was hitting both the limits when I was doing some benchmarks locally, so increased the limits for the benchmark.

Also, I would need calling `b.ResetTimer()` and `b.ReportAllocs()` for the benchmark, so the common code would be the one before that.

**Comment by bboreham** [comment]
If you can explain why the limits need to be different, please put that in a comment.
If not, remove the difference.

I don't usually put `ReportAllocs()` in the code because it is available as a command-line option `-benchmem`

**Comment by codesome** [comment]
Made the limits same, and removed `b.ReportAllocs()`.

**Comment by bboreham** [comment]
so more of the code can be shared now?

**Comment by codesome** [comment]
`b.ResetTimer()` was in between. I will try sharing more code.

**Comment by codesome** [comment]
And done!

**Comment by tomwilkie** [comment]
:+1: LGTM

**Pull request merged**
