### PR TITLE
Add CORTEX_CHECKOUT_PATH env variable to CI

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by gliptak** [comment]
Integration test failure seems to be unrelated
```
2021-06-20T10:26:50.8856827Z     chunks_storage_backends_test.go:85: 
2021-06-20T10:26:50.8857447Z         	Error Trace:	chunks_storage_backends_test.go:85
2021-06-20T10:26:50.8858095Z         	Error:      	Received unexpected error:
2021-06-20T10:26:50.8859029Z         	            	unable to find metrics [cortex_table_manager_sync_success_timestamp_seconds] with expected values. Last error: <nil>. Last values: [0]
2021-06-20T10:26:50.8860176Z         	Test:       	TestChunksStorageAllIndexBackends
2021-06-20T10:26:50.8861117Z 10:11:18 Killing table-manager
2021-06-20T10:26:50.8861768Z 10:11:18 Killing consul
2021-06-20T10:26:50.8862213Z 10:11:19 Killing bigtable
2021-06-20T10:26:50.8862808Z 10:11:19 Killing dynamodb
2021-06-20T10:26:50.8863403Z 10:11:19 Killing cassandra
2021-06-20T10:26:50.8864481Z --- FAIL: TestChunksStorageAllIndexBackends (46.95s)
```

**Review by stevesg — APPROVED** [review]
Looks good, I don't see a good reason not to do this, but I am curious what this enables? Does my make it easier to run the CI locally, or from a fork, or something else?

**Comment by gliptak** [comment]
@stevesg just makes the file more readable. I have a followup PR which removes dependency on publishing build-image, it builds Dockerfile in-line and uses build-image in successor steps https://github.com/gliptak/cortex/pull/2/files

**Comment by pstibrany** [comment]
> @stevesg just makes the file more readable. I have a followup PR which removes dependency on publishing build-image, it builds Dockerfile in-line and uses build-image in successor steps https://github.com/gliptak/cortex/pull/2/files

I don't think this is a good idea. Rebuilding image on each build will make slow Cortex builds even slower. We would prefer to speed up the builds instead.

**Comment by gliptak** [comment]
@pstibrany yes there is some overhead. you gain the benefit of in-line validation of the build-image Dockerfile and remove the requirement of pre-publishing Dockerfile updates so you can work issues like https://github.com/cortexproject/cortex/issues/4300

**Comment by gliptak** [comment]
@pstibrany to speedup the build, maybe the integration tests could be separated into 2-3 sections running in parallel https://github.com/cortexproject/cortex/pull/4299/checks?check_run_id=2874246023 (I haven't looked into dependencies between  and of individual integration tests)

**Comment by pstibrany** [comment]
> yes there is some overhead. you gain the benefit of in-line validation of the build-image Dockerfile and remove the requirement of pre-publishing Dockerfile updates so you can work issues like #4300

I think the cost-to-benefit ratio is very bad here. Build image doesn't change so often to add few extra minutes to every single build. I think that's a bad tradeoff.

> to speedup the build, maybe the integration tests could be separated into 2-3 sections running in parallel https://github.com/cortexproject/cortex/pull/4299/checks?check_run_id=2874246023 (I haven't looked into dependencies between and of individual integration tests)

Yes, if that's something you can help us with, that would be wonderful. There should be no dependencies between individual tests, except for reuse of docker container names and docker network to avoid leaving stuff behind.

**Comment by pracucci** [comment]
> I think the cost-to-benefit ratio is very bad here. Build image doesn't change so often to add few extra minutes to every single build. I think that's a bad tradeoff.

I agree.

**Comment by pracucci** [comment]
>> Looks good, I don't see a good reason not to do this, but I am curious what this enables? Does it make it easier to run the CI locally, or from a fork, or something else?
> just makes the file more readable

If it's just an aesthetic change, then I'm a bit dubious about this PR.

**Pull request closed without merging**
