### PR TITLE
Upgrade Prometheus to latest master

### PR DESCRIPTION
**Pull request by codesome**
**What this PR does**:

Upgrades Prometheus to current master to get the following fixes in:
* https://github.com/prometheus/prometheus/commit/2fe1e9fa93772fd831b1c040968bb748eac12795
* https://github.com/prometheus/prometheus/commit/2624d827fadc604323db979e1d7b59415531f3d3
* https://github.com/prometheus/prometheus/commit/c5a832b39440547f681dc08f06343c79d5ba7f45
* https://github.com/prometheus/prometheus/commit/3245b3267b24a99bd46ac60d5cf7c08c7496ac2a

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by pracucci** [comment]
@codesome FYI I pushed a fixed to a test.

**Review by pracucci — APPROVED** [review]
LGTM, thanks!

**Comment by pracucci** [comment]
A test is segfaulting:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11e3e06]

goroutine 14618 [running]:
github.com/prometheus/prometheus/tsdb.(*DB).Close(0x0, 0x0, 0x0)
	/go/src/github.com/cortexproject/cortex/vendor/github.com/prometheus/prometheus/tsdb/db.go:1328 +0x56
github.com/prometheus/prometheus/tsdb.open.func1(0xc0046f3a68, 0xc0046f3a60)
	/go/src/github.com/cortexproject/cortex/vendor/github.com/prometheus/prometheus/tsdb/db.go:606 +0x20f
github.com/prometheus/prometheus/tsdb.open(0xc001cf1040, 0x18, 0x22e8b80, 0xc00286aba0, 0x230e1a0, 0xc003035270, 0xc0030352c0, 0xc0070dd2c0, 0x1, 0xa, ...)
	/go/src/github.com/cortexproject/cortex/vendor/github.com/prometheus/prometheus/tsdb/db.go:651 +0x1208
github.com/prometheus/prometheus/tsdb.Open(0xc001cf1040, 0x18, 0x22e8b80, 0xc00286aba0, 0x230e1a0, 0xc003035270, 0xc0030352c0, 0xc00bfa9c70, 0x0, 0x0)
	/go/src/github.com/cortexproject/cortex/vendor/github.com/prometheus/prometheus/tsdb/db.go:530 +0xdc
github.com/cortexproject/cortex/pkg/ingester.(*Ingester).createTSDB(0xc009f36900, 0xc0031a82d3, 0x5, 0x11dbe0e, 0xc009a26180, 0xc006ac55f4)
	/go/src/github.com/cortexproject/cortex/pkg/ingester/ingester_v2.go:994 +0xb50
github.com/cortexproject/cortex/pkg/ingester.(*Ingester).openExistingTSDB.func1.1(0xc0031981f0, 0xc00c892bb8, 0xc009f36900, 0xc003198200, 0xc0042ba1e0, 0xc0031a82d3, 0x5)
	/go/src/github.com/cortexproject/cortex/pkg/ingester/ingester_v2.go:1147 +0x192
created by github.com/cortexproject/cortex/pkg/ingester.(*Ingester).openExistingTSDB.func1
	/go/src/github.com/cortexproject/cortex/pkg/ingester/ingester_v2.go:1140 +0x15c4
FAIL	github.com/cortexproject/cortex/pkg/ingester	38.469s
FAIL
```

**Comment by codesome** [comment]
I think https://github.com/prometheus/prometheus/pull/8113 should fix the panic

**Comment by codesome** [comment]
I have updated the PR to include https://github.com/prometheus/prometheus/commit/3245b3267b24a99bd46ac60d5cf7c08c7496ac2a, hope everything is fine this time :crossed_fingers:

**Review by pracucci — APPROVED** [review]
I double checked the changes and LGTM! Only one comment: I think it would be worth to mention in the `CHANGELOG` the `[BUGFIX]` included in this upgrade, because they've a significative impact on Cortex users running the blocks storage.

**Review by csmarchbanks — APPROVED** [review]

**Pull request merged**
