### PR TITLE
reorder cortex config reference

### PR DESCRIPTION
**Pull request by fbegyn**
**What this PR does**:

A reference should either have a logical or alpanumeric order. The previous layout had neither, which made navigating the reference quite a challenge IMHO.

I've restructered the reference to be alphanumeric order, which makes navigating the page easier.

**Checklist**
- [x] Tests updated
- [x] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by friedrichg — CHANGES_REQUESTED** [review]
Thanks for your contribution!.

The only thing is this doc is generated from code, so the code should be fixed to generate the ordered output.

Here are some hints:
https://github.com/cortexproject/cortex/blob/47733ddab802acef66f6ab7be41ebb24a512a7ce/Makefile#L263
https://github.com/cortexproject/cortex/blob/47733ddab802acef66f6ab7be41ebb24a512a7ce/tools/doc-generator/main.go#L48-L49

**Comment by fbegyn** [comment]
> The only thing is this doc is generated from code

I somehow missed this, but it's updated now. I've done it manually in the order blocks since it specifies

```
	// Ordered list of root blocks. The order is the same order that will
	// follow the markdown generation.
```

Seeing this made me wonder: 

* was there an order I just steamrolled over?
* there is an opportunity to also do this dynamically by implementing a `sort.Sort` for the doc `blocks`. Would this be preferred?

**Review by friedrichg — APPROVED** [review]
I think calling order will just encourage developers to create messy code, which will be hard to read and maintain. Your fix is just fine.

**Review by alanprot — APPROVED** [review]

**Comment by alanprot** [comment]
Thanks! LGTM

**Pull request merged**
