### PR TITLE
Fixes `-config.expand-env` requires argument.

### LINKED ISSUE #3082: -config.expand-env requires argument
If not provided an argument, `-config.expand-env` fails parsing/validation and causes an exit. Easily reproducible with `./cortex -config.expand-env`.
The working usage seems to be `-config.expand-env=true`. 

While the documentation isn't completely clear on the topic, my reading is at least that `-config.expand-env` does not require any argument:
https://github.com/cortexproject/cortex/blob/a87c25fd994a2eec5ab5af0a920cc529b17c0030/docs/configuration/config-file-reference.md#L31

The various unit tests in [main_test.go](https://github.com/cortexproject/cortex/blob/2cbf61af6ed31a811376795a8f9721b890a6e36f/cmd/cortex/main_test.go) seem to get around this somehow?

As a side-note, passing non-boolean arguments is silently accepted as false, for example `-config.expand-env=FOO` would **not** lead to `${FOO}` being expanded, but kept verbatim in the file. I tested that variety since I've used other systems in the past where a list of allowed environment variables needs to be passed, not sure if that would be a common reasoning.

### PR DESCRIPTION
**Pull request by Wing924**
Signed-off-by: Wing924 <weihe924stephen@gmail.com>

**What this PR does**:

old:
```
% docker run --rm  quay.io/cortexproject/cortex:v1.3.0 -config.expand-env
flag needs an argument: -config.expand-env
Run with -help to get list of available parameters
```

new:
```
-> % docker run --rm quay.io/cortexproject/cortex -config.expand-env
level=info ts=2020-08-25T08:41:46.0276577Z caller=main.go:162 msg="Starting Cortex" version="(version=1.3.0, branch=master, revision=2cbf61af6)"
level=info ts=2020-08-25T08:41:46.0283108Z caller=server.go:223 http=[::]:80 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2020-08-25T08:41:46.0287076Z caller=modules.go:488 msg="RulerStorage is not configured in single binary mode and will not be started."
level=error ts=2020-08-25T08:41:46.0300884Z caller=log.go:143 msg="error running cortex" err="schema config file needs to be set\nerror initialising module: table-manager\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/go/src/github.com/cortexproject/cortex/pkg/util/modules/modules.go:89\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).Run\n\t/go/src/github.com/cortexproject/cortex/pkg/cortex/cortex.go:282\nmain.main\n\t/go/src/github.com/cortexproject/cortex/cmd/cortex/main.go:164\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"
```

**Which issue(s) this PR fixes**:
Fixes #3082

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by bboreham — APPROVED** [review]
Thanks.

**Review by pracucci — APPROVED** [review]
Thanks!

**Comment by pracucci** [comment]
@Wing924 There's apparently some issue triggering the CI for your commits. Could you try to login to circleci.com, unfollow cortex, follow it again, and then git push force this PR again, please? That's what CircleCI customer support suggested me last time I opened a ticket for this issue.

**Comment by Wing924** [comment]
created a new PR to avoid circleci issue: #3087

**Pull request closed without merging**
