### PR TITLE
Update weaveworks common

### PR DESCRIPTION
**Pull request by nrjpoddar**
Fixes: #1279

### CODE REVIEW

**Comment by nrjpoddar** [comment]
@bboreham PTAL

**Comment by bboreham** [comment]
Thanks.  

In addition to the item linked (Skip logging context cancelled warning msgs - https://github.com/weaveworks/common/pull/151), this PR brings in a number of other changes:

- Update to latest kuberesolver https://github.com/weaveworks/common/pull/131
- Allow server.Config to be unmarshaled from YAML. https://github.com/weaveworks/common/pull/132
- Log which ports the server is listening on. (https://github.com/weaveworks/common/pull/143) 
- server: add PathPrefix to config for all routes https://github.com/weaveworks/common/pull/144
- Allow overriding max message sizes and concurrent streams in the server. https://github.com/weaveworks/common/pull/146
- Dont flag context.Canceled as an error in tracing https://github.com/weaveworks/common/pull/148
- exclude Authorization headers from log messages. https://github.com/weaveworks/common/pull/149
- server: use -server.path-prefix for metrics and debug endpoints https://github.com/weaveworks/common/pull/150
- Allow log levels to be marshalled to YAML. https://github.com/weaveworks/common/pull/152

[Full list of commits](https://github.com/weaveworks/common/compare/c1808abf9c...87611edc25)

**Comment by nrjpoddar** [comment]
@bboreham should I include this list as part of my commit message?

**Comment by nrjpoddar** [comment]
can this be merged? I don't have merge permissions.

**Comment by bboreham** [comment]
It is awaiting a second review as required by our [rules](https://github.com/cortexproject/cortex/blob/master/GOVERNANCE.md)

I don't need you to change anything, although you might take it as a guide to what is useful to know when reviewing a change.

**Pull request merged**
