### PR TITLE
export distributor properties to make ingester extendable

### PR DESCRIPTION
**Pull request by replay**
I would like to add an additional GRPC call to the Ingester service, to query that additional call it would be nice if I could re-use the existing Ingester querying code in the Distributor. To make that possible the following two properties would need to be exported:

`Distributor.forAllIngesters()` 
By exporting this method I'll be able to query all Ingesters by calling `distributor.ForAllIngesters()` with a custom function which type-casts the Ingester client to one that supports my additional call, like this:
```
responses, err := dist.ForAllIngesters(ctx, true, func(client ingesterClient.IngesterClient) (interface{}, error) {
    extendedClient := client.(extendedIngester.ExtendedIngesterClient)
    resp, err := extendedClient.MyCustomCall(ctx, req)
    if err != nil {
        return nil, err
    }
    return resp, nil
})
```

`Config.ingesterClientFactory`
To make the Distributor instantiate clients of my extended type I'll also need to set the client factory in the Distributor config, like this:

```
distributorCfg.IngesterClientFactory = func(addr string) (ring_client.PoolClient, error) {
		return extendedIngester.MakeClient(addr, IngesterClient)
	}
```

What do you think about doing it this way?

### CODE REVIEW

**Comment by pstibrany** [comment]
> What do you think about doing it this way?

I'm fine with this approach.

**Comment by replay** [comment]
> I'm fine with this approach.

Great, I'll fix the tests

**Review by jtlisi — APPROVED** [review]
LGTM

**Review by pstibrany — APPROVED** [review]
LGTM.

**Pull request merged**
