### PR TITLE
Reintroduce pkg/util/backoff in place of dskit/backoff

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does**:
Reintroduce pkg/util/backoff in place of dskit/backoff.

**Which issue(s) this PR fixes**:

**Checklist**
- [x] Tests updated
- [na] Documentation added
- [na] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by pracucci** [comment]
Could you take a look at the failing test? I thought it was flaky but it failed for few consecutive CI runs 🤔

**Comment by aknuds1** [comment]
> Could you take a look at the failing test? I thought it was flaky but it failed for few consecutive CI runs thinking

@pracucci will do.

**Comment by aknuds1** [comment]
@pracucci I think it was a flake after all, since the tests now passed. I also could not reproduce the failure at all locally.

**Review by pracucci — APPROVED** [review]
Thanks!

**Pull request merged**
