### PR TITLE
[WIP] Revert "Revert "Remove default for database flag""

### PR DESCRIPTION
**Pull request by jml**
Reverts weaveworks/cortex#710

### CODE REVIEW

**Comment by bboreham** [comment]
Why?

**Comment by jml** [comment]
The original motivation for the change hasn't gone away, it just needs to be done properly. Hence a WIP PR.

**Comment by tomwilkie** [comment]
This PR is over 7 months old now - do you think we should close it?

**Comment by jml** [comment]
Yes

**Pull request closed without merging**
