### PR TITLE
Dashboard s3.jsonnet

### PR DESCRIPTION
**Pull request by till**
Pushing this mostly to see if this is interesting for someone else.

**What this PR does**:

 1. Adds an `s3.libsonnet` file as currently only bigtable is offered.
 2. Fixes (a bug?) in the dashboard files, memcache methods must have been renamed.

**Checklist**
- [x] ~~Tests updated~~
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by pstibrany** [comment]
Hello and thank you for your contribution. I believe that these libsonnet files are now maintained in separate repository, https://github.com/grafana/cortex-jsonnet (in `cortex-mixin` subdirectory) Would you be interested in sending your PR there?

**Comment by till** [comment]
Oh, sure. I'll update the readme here then? What do you think?

**Comment by pstibrany** [comment]
> Oh, sure. I'll update the readme here then? What do you think?

That's a good idea, thank you.

**Comment by pracucci** [comment]
> Oh, sure. I'll update the readme here then? What do you think?

Could you open a separate PR for that? _I'm going to close this PR since we agreed that these mixins are outdated (I'm also going to start a conversation about removing them at all)._

**Comment by pstibrany** [comment]
> I'm also going to start a conversation about removing them at all

+1 from me.

**Pull request closed without merging**
