### PR TITLE
Count the chunks stored per user.

### PR DESCRIPTION
**Pull request by gouthamve**
Since with object storage, the create operation is going to cost
significant $$$, we need to measure the number of creates also.

CHANGE
metric name: `cortex_ingester_chunk_bytes_total` --> `cortex_ingester_chunk_bytes_stored_total`

Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>

### CODE REVIEW

**Comment by bboreham** [comment]
Please flag up breaking changes (here, the metric name) in descriptions.

**Comment by gouthamve** [comment]
Sorry, should have noted that. Did that now.

**Comment by bboreham** [comment]
Now I am wondering about the new names.
https://prometheus.io/docs/practices/naming/#metric-names says the unit should be a suffix.
Should it be:
`cortex_ingester_chunks_stored_total`
and 
`cortex_ingester_chunks_stored_bytes_total` ?

**Comment by gouthamve** [comment]
@bboreham You're right, I modified the metric names

**Pull request merged**
