### PR TITLE
Updated Thanos to 0.8.1

### PR DESCRIPTION
**Pull request by pracucci**
**What this PR does**:
Updated Thanos - used by the experimental TSDB storage integration - from `0.7.0` to `0.8.1`. From the TSDB integration perspective, I've checked out the changes and should be safe: it introduces the new sharding based on relabelling (which we're not using right now) and few fixes / refactoring.

**Which issue(s) this PR fixes**:
_No issue_

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### Vendor changes analysis

```
- # github.com/grpc-ecosystem/go-grpc-middleware v1.0.1-0.20190118093823-f849b5445de4
+ # github.com/grpc-ecosystem/go-grpc-middleware v1.1.0
```

No breaking changes in the [release notes](https://github.com/grpc-ecosystem/go-grpc-middleware/releases/tag/v1.1.0). Also checking the [diff](https://github.com/grpc-ecosystem/go-grpc-middleware/compare/f849b5445de4...v1.1.0) I don't see anything that may negatively affect us.

```
- # golang.org/x/net v0.0.0-20190724013045-ca1201d0de80
+ # golang.org/x/net v0.0.0-20190923162816-aa69164e4478
```

Looking at the diff, I can see a couple of change that shouldn't affect us:
- HTTP2: introduced `maxQueuedControlFrames = 10000` which is the maximum number of control frames like SETTINGS, PING and RST_STREAM that will be queued for writing before the connection is closed to prevent memory exhaustion attacks.
- HTTP2: on the client side, fail if the request body is longer than the declared `Content-Length`

```
- # google.golang.org/api v0.8.0
+ # google.golang.org/api v0.11.0
```

Looking at the diff, I can see only changes to the Google API mappings (cloudresourcemanager, compute, storage). Looks they've added new features. In particular, to the storage they've added support to `OptionsRequestedPolicyVersion` IAM policy.

```
- # github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
+ # github.com/grpc-ecosystem/go-grpc-prometheus v1.2.1-0.20191002090509-6af20e3a5340
```

Looking at the diff, they introduced requirement upped the Go requirement to `1.9`, support for error unwrapping and a function to enable client receive/send time histogram (default hasn't changed).

```
- # github.com/jessevdk/go-flags v0.0.0-20180331124232-1c38ed7ad0cc
+ # github.com/jessevdk/go-flags v1.4.0
```

The module is now versioned. They removed `env-namespace` support, which we don't use.

```
- # github.com/miekg/dns v1.1.15
- # github.com/miekg/dns v1.1.19
```

[Looking at the diff](https://github.com/miekg/dns/compare/v1.1.15...v1.1.19), they removed Go `1.10` support, switched to Go modules, done several perf improvements.

```
- # github.com/uber/jaeger-lib v2.0.0+incompatible
+ # github.com/uber/jaeger-lib v2.2.0+incompatible
```

Looking at the diff, no code changes for us.

```
- # golang.org/x/crypto v0.0.0-20190701094942-4def268fd1a4
+ # golang.org/x/crypto v0.0.0-20191002192127-34f69633bfdc
```

No changes for us.

```
- # golang.org/x/sys v0.0.0-20190826190057-c7b8b68b1456
+ # golang.org/x/sys v0.0.0-20190924154521-2837fb4f24fe
```

[Looking at the diff](https://github.com/golang/sys/compare/c7b8b68b1456...2837fb4f24fe), excluding Windows stuff, I see several fixed but no breaking changes.

### CODE REVIEW

**Comment by pracucci** [comment]
What's your take @thorfour?

**Comment by thorfour** [comment]
Based on the changes I'm aware of that sounds good to me

**Comment by bboreham** [comment]
Please can you call out the dependencies also updated - e.g. `github.com/grpc-ecosystem/go-grpc-middleware`, `golang.org/x` and check if there are any changes we should be aware of.

**Comment by pracucci** [comment]
> Please can you call out the dependencies also updated - e.g. github.com/grpc-ecosystem/go-grpc-middleware, golang.org/x and check if there are any changes we should be aware of.

@bboreham I've updated the PR description with the summary of my analysis on changes. All changes look safe to my eyes.

**Comment by owen-d** [comment]
This looks good

**Pull request merged**
