### PR TITLE
upgrade thanos to latest main and update Prometheus

### PR DESCRIPTION
**Pull request by yeya24**
**What this PR does**:

Update Thanos to https://github.com/thanos-io/thanos/pull/7813 and Prometheus accordingly.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by yeya24** [comment]
Hey @harry671003, can you please help review this change when you have time? There are some changes related to the labels API limit.

**Review by harry671003 — APPROVED** [review]
LGTM!
I only looked at pkg/ changes.

**Comment by harry671003** [comment]
Prometheus is from a month ago. https://github.com/prometheus/prometheus/commit/6f0d6038b7f9
Are we still blocked on the Thanos PromQL engine update for latest Prometheus?

**Comment by yeya24** [comment]
@harry671003 IIUC we are still blocked as it doesn't have https://github.com/prometheus/prometheus/commit/debbdb8608cdd24e0cfcd1046f04ea4c6abd840e#diff-ad2761bb162a2f12326b18f2714ef54f4cd476cfe3388f77b2b20c5ff82e4faaR899.

Update to this commit to pull some of the upstream changes for now. We still need to resolve the issue on Thanos promql engine side.

**Review by alanprot — APPROVED** [review]

**Pull request merged**
