### PR TITLE
Modified TestWatchKey test to make it less strict.

### PR DESCRIPTION
**Pull request by pstibrany**
Test now uses longer waits between time updates, has longer total time (3s) and expects to see fewer values (75%).

At the same time, test uses same structure as TestWatchPrefix:
- start watcher early, before generator even starts
- report observed values through buffered channel
- end test early if we have seen enough values

Fixes issue #1800.

### CODE REVIEW

**Comment by pstibrany** [comment]
> I'm wondering if we could rewrite the test using a `sync.Cond` used by `client.CAS()` goroutine and `client.WatchKey()` gorouting. We CAS once then `cond.Wait()`, then the `client.WatchKey()` will file and we assert there and call `cond.Signal()` so that another CAS will occur, and so on. The expected behaviour is that any `CAS()` will have triggered a `WatchKey()`. Makes sense?

I think we can achieve the same behaviour by using unbuffered channel.

**Comment by pracucci** [comment]
> I think we can achieve the same behaviour by using unbuffered channel.

Right, should be the same, agree.

**Comment by pstibrany** [comment]
> Right, should be the same, agree.

Actually, it's not... your suggestion is about syncing CAS and WatchKey, while buffered channel would sync watcher and reporting goroutine.

Anyway, question is what do we even test here. When doing watching test, I think we need to make sure that 1) we are receiving *some* watch notifications, 2) we have seen the latest one [we don't check for this].

You are right that it may still flake under bad conditions. But I think adding sync between sender and notifications defeats the purpose of the test.

**Comment by pracucci** [comment]
> But I think adding sync between sender and notifications defeats the purpose of the test.

I see your point. I don't have a better suggestion, and the proposed change improve the situation, so consider it still approved by me 😉

**Comment by pracucci** [comment]
@pstibrany Could you rebase just to make sure tests still pass? I remember I did extensively review this (non trivial) code change and LGTM.

**Comment by pstibrany** [comment]
Rebased. 🤞

**Comment by pracucci** [comment]
Today we've got [another CI run failing because of this](https://circleci.com/gh/cortexproject/cortex/16291):
```
--- FAIL: TestWatchKey (4.18s)
    --- FAIL: TestWatchKey/etcd (2.18s)
        kv_test.go:141: expected at least 90% observed values, got 89% (observed count: 89)
```

I think this PR would solve (or at least reduce the change of) this flaky test.

**Pull request merged**
