### PR TITLE
[WIP] schema/table migration tool

### PR DESCRIPTION
**Pull request by jtlisi**
This PR adds a set of tooling that allows user to migrate chunks between storage backend. It will also allow users to update the chunk schema of chunks in their backend in an offline manner.

_migrate-writer_
implements TransferChunks server proto and accepts and stores a streams of chunks

_migrate-reader_
Uses the `StreamChunks` method from the chunkstore and streams chunks to a migrate-writer. 

### Changes of Note
* StreamChunks method added to chunkstore interface
* StreamBatch interface and methods added to chunkstore
* Add metric fingerprint in FromChunks (compat.go) function

### CODE REVIEW

**Comment by bboreham** [comment]
I've been writing various bulk-scanning programs on AWS; you need to run on multiple goroutines for best performance.  So I put multiple callbacks into the API and made it work like `QueryPages()`.

At some point I will need to go across multiple processes, so will need more parameters to segment the read.

**Comment by bboreham** [comment]
You can take a look at https://github.com/cortexproject/cortex/blob/dynamodb-scanning/pkg/chunk/aws/scanner.go - this is not polished and doesn't support multi-process sharding, but it gets the job done.

The DynamoDB API lets you tell it how many "segments" will be scanning in total, and then in theory you can run them from wherever you like.

**Comment by mfischer90** [comment]
@jtlisi Hi, are you planning to support DynamoDB with this feature? If not, is there something we can do to help/contribute?

**Comment by jtlisi** [comment]
I tested this PR in it's current state and chunks are successfully re-encoded before writing. Legacy formatted row keys will no longer occur in the index

**Comment by mfischer90** [comment]
@jtlisi Hi, are you planning to support DynamoDB with this feature? If not, is there something we can do to help/contribute?

**Comment by jtlisi** [comment]
@mfischer90 I was planning on adding a dynamodb path. However, I have not gotten around to it yet. 
I was planning on using @bboreham's https://github.com/cortexproject/cortex/tree/simple-scanner branch as a guide. Applying the concept of shards to segments seems very straightforward. If you want to tackle implementing that I would really appreciate it.

**Pull request closed without merging**
