### PR TITLE
WIP (chore) deps: update migrated dependency mattes/migrate->golang-migrate/migrate

### PR DESCRIPTION
**Pull request by jan25**
`github.com/mattes/migrate` has moved to `github.com/golang-migrate/migrate`
So, this PR updates current dependency to use `gopkg.in/golang-migrate/migrate.v1`

Fixes: #1384 

Signed-off-by: Abhilash Gnan <abhilashgnan@gmail.com>

Notes:
Although this PR fixes the migrated dependency, the migrate.v1 may not be supported according to [this](https://github.com/golang-migrate/migrate#versions). Should we consider using v4?

### CODE REVIEW

**Comment by jtlisi** [comment]
If you could upgrade to V4 that would probably be fine. You will have to update the SyncUp command I believe 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tomwilkie** [comment]
Thanks @jan25! LGTM from me on this, although feel free to try the update to v4 too.

**Comment by jan25** [comment]
Thanks for the review! I'm trying to use v4. Tests looked good on local. But CI failed in this PR
Do you think i could get permission to re-run the build?

**Comment by jan25** [comment]
Also, i think the `go mod` trigerred too many minor version updates to several other dependencies. So there are a lot of changes to vendor folder

**Comment by jan25** [comment]
Closing this temporarily. Will look into it when i have time, meanwhile someone else can take a look if possible. Thanks!

**Pull request closed without merging**
