### PR TITLE
support Baidu Object Storage (bos)

### PR DESCRIPTION
**Pull request by sequix**
Signed-off-by: sequix <sequix@163.com>

Hi everyone, I am a programmer from Baidu. Our team want to build a log inspect center with grafana/loki based on our own object storage Baidu Object Storage(BOS). So I made this PR.

### CODE REVIEW

**Comment by gouthamve** [comment]
Hey curious, does BOS support an S3 interface?

**Comment by sequix** [comment]
very similar, I even doubt that the BOS team is mimicing s3.

**Comment by gouthamve** [comment]
If that is the case, you can use the existing the S3 support to write and read from Baidu. DigitalOcean Object Storage does the same.

Could you join the slack here: https://cloud-native.slack.com/messages/cortex/ to quickly chat through this? To invite yourself to the CNCF Slack, visit http://slack.cncf.io/.

**Comment by sequix** [comment]
oh, I just found BOS provide a aws-compatible API set, sorry for interrupt, close PR.

**Pull request closed without merging**
