### PR TITLE
Update prometheus-frontend.md

### PR DESCRIPTION
**Pull request by fsperling**
I think if you are running the Cortex query frontend alone you basically always want to / need to configure the downstream_url.
Therefore it should be part of the default config for this usecase.

### CODE REVIEW

**Comment by pracucci** [comment]
@fsperling Would you mind signing your commit, please? It's just a git command to run. If don't know how it works, you can find the instructions [here](https://cortexmetrics.io/docs/contributing/#developer-certificates-of-origin-dcos).

**Comment by fsperling** [comment]
I tried to sign it but the DCO is still red. Not sure if it worked or not.

**Comment by pracucci** [comment]
Thanks @fsperling. I think you signedoff my last commit, but not your original one (see here: https://github.com/cortexproject/cortex/pull/2492/commits). You can `git rebase -i HEAD~2` and then reword the first commit to add the signature.

**Comment by fsperling** [comment]
Don't think that changed anything.

**Comment by pracucci** [comment]
@fsperling Legally I can't sign it for you, so please try the following:

1. `git rebase -i HEAD~2`
2. It will open a text editor. Change the first line from `pick 130ce5c3d Update prometheus-frontend.md` to `r 130ce5c3d Update prometheus-frontend.md`
3. It will open another text editor. Append **at the end** (in a new line) of the commit message: `Signed-off-by: Felix Sperling <felix.sperling@idealo.de>`
4. `git push --force`

**Pull request merged**
