### PR TITLE
Implement quorum reads and merging for /v2/alerts and /v2/alerts/groups.

### PR DESCRIPTION
**Pull request by stevesg**
**What this PR does**:

Reading alert listings via /v2/alerts and /v2/alerts/groups will now
read from a quorum of replicas and return a merged response.

Alerts are merged by returning the union of alerts over all responses.
When multiple responses contain the same alert, the alert with the most
recent "updatedAt" timestamp is chosen. Groups are returned by returning
the union of groups over all responses. When the same group is present in
multiple responses (same receiver and labels fingerprint), the groups are
merged into by merging the sets of alerts in each.

**Checklist**
- [X] Tests updated
- [X] ~~Documentation added~~
- [X] ~~`CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`~~

### CODE REVIEW

**Review by pstibrany — APPROVED** [review]
Nice job, especially the unit tests!

**Comment by gouthamve** [comment]
Can you please rebase against master to pull in https://github.com/cortexproject/cortex/pull/4137 and move the changelog entry to the top?

**Review by pracucci — APPROVED** [review]
Amazing job! Looks flawless to me 👏

**Comment by pstibrany** [comment]
Does this (and previous) PR need a changelog entry?

**Comment by pracucci** [comment]
> Does this (and previous) PR need a changelog entry?

Right! The whole alertmanager sharding work is missing a CHANGELOG entry. @stevesg I think it's time to open a PR with that, given the work is getting done.

**Pull request merged**
