### PR TITLE
Bump Ubuntu to 20.04 in CI

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

**What this PR does**:

https://github.com/actions/virtual-environments/issues/3287

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by jtlisi** [comment]
If we are going to upgrade ubuntu for the CICD process, we may be better off upgrading to 20.04. @gliptak WDYT?

**Review by jtlisi — APPROVED** [review]
LGTM

**Comment by gliptak** [comment]
@jtlisi there are also ubuntu-latest references. For reproducibility (and stability), I recommend setting all references to ubuntu-20.04

let me know if I'm to update this PR accordingly

**Comment by pracucci** [comment]
> @jtlisi there are also ubuntu-latest references. For reproducibility (and stability), I recommend setting all references to ubuntu-20.04
> 
> let me know if I'm to update this PR accordingly

You're right. We should always specify the version for a better stability (instead of using `ubuntu-latest`). Could you fix it in this PR, setting all references to `ubuntu-20.04` as you suggested, please? 🙏

**Review by pracucci — APPROVED** [review]
CI passes, so LGTM 😉

**Pull request merged**
