### PR TITLE
Adds the ability the fetch label values from the store

### PR DESCRIPTION
**Pull request by Kuqd**
Signed-off-by: Cyril Tovena <cyril.tovena@gmail.com>

This is required to advance https://github.com/grafana/loki/issues/453 in Loki.

I also need to add `LabelNames(metricName, start, end)` but since this is my first PR I wanted to have a quick feedback on this first.

### CODE REVIEW

**Comment by bboreham** [comment]
Thanks for the PR; it looks promising.  This isn't the same as the Prometheus API `LabelValues`, right?  Because that one doesn't have a metric name.  I think you should mention that in a comment, and possibly use a different name.

I would probably also split the change into two commits containing the refactor of `validateQueryTimeRange()` and then the new code.

**Comment by Kuqd** [comment]
Not exactly like https://prometheus.io/docs/prometheus/latest/querying/api/#querying-label-values as it requires the metric name like you said.

I'll see how I can split the commit. I actually intentionally squash rebased it to a single commit, since I was used to it for other project.

**Comment by Kuqd** [comment]
Could not find a better name but I did add a documentation.

PTAL

**Comment by bboreham** [comment]
Given that we have `LabelValuesForLabelName()` elsewhere, how about `LabelValuesForMetricName()` here?

**Comment by bboreham** [comment]
Besides the name, LGTM

**Comment by tomwilkie** [comment]
Nice work Cyril!  LGTM too.

**Pull request merged**
