### PR TITLE
Implement quorum reads and merging for /v2/silences and /v2/silence/id

### PR DESCRIPTION
**Pull request by stevesg**
**What this PR does**:

Reading silence listings and individual silences will now read from a
quorum of replicas and return a merged response. In both cases, in the
presence of duplicate silences with the same "id", the silence with the
most recent "updatedAt" timestamp is return.

Note that this does not yet bring full consistency to silences, as we
are not able to perform quorum writing of silences without upstream
changes to Alertmanager.

However, it will still be an improvement:
- Reads will be consistent more often, being able to take state from
  multiple replicas instead of just one.
- Requests will be resilient to single replica failure, as the request
  is essentially attempted on all three replicas.

A possible extension to this change would be to block for all replicas
to reply, but still allow a single failure. This would mean that reads
are consistent for the case when all replicas are contactable.

**Checklist**
- [X] Tests updated
- [X] ~~Documentation added~~
- [X] ~~`CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`~~

### CODE REVIEW

**Review by pstibrany — APPROVED** [review]
Nice job!

(nit: Having one type per file seems like Javaism, and not something we normally do in Go. But it explains why you created whole new package for it :). Perhaps we can merge all v2 stuff into single v2.go file?)

**Comment by stevesg** [comment]
> (nit: Having one type per file seems like Javaism, and not something we normally do in Go. But it explains why you created whole new package for it :). Perhaps we can merge all v2 stuff into single v2.go file?)

Haha, fair comment. When I started the mergers were a lot more complicated, so I think it made sense.

(However, and old colleague of mine said the opposite - "In Go we have no problem breaking code up into lots of files"!)

**Review by gotjosh — APPROVED** [review]
LGTM

**Review by pracucci — APPROVED** [review]
Fantastic job! Keep doing such great work! 👏 👏 👏

**Pull request merged**
