### PR TITLE
Fixing how ring ownership is calculated on the ring status page

### PR DESCRIPTION
**Pull request by alanprot**
**What this PR does**:

This PR include 3 changes:
* Fix how the ring owership is calculated on the ring status page
  * Before we were calculating the distance from the token to the next one, but instead, we should calculate the distance from the previous one.
  * If AZ aware is enabled, only take tokens from the ingester AZ to calculate the ownership
  * Add a column to show the difference in percentual from the expected ownership to the actual ownership.  
Screenshot 2024-04-24 at 5 26 33 PM

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [NA] Tests updated
- [NA] Documentation added
- [X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by yeya24 — APPROVED** [review]
Thanks

**Comment by yeya24** [comment]
Test failure is related

**Comment by yeya24** [comment]
I don't see changelog has been added. Should we mention the new column added?

**Comment by alanprot** [comment]
> I don't see changelog has been added. Should we mention the new column added?

Done :D

**Pull request merged**
