### PR TITLE
Document the logic behind cardinality limits.

### PR DESCRIPTION
**Pull request by gouthamve**
~We're not loading the chunks in the initial queries, instead just
figuring out which series have to be loaded. I don't think it makes
sense to enforce cardinality limits on queries that return seriesIDs
which will be intersected away.~

~Here, I made the changes to make sure only the final intersected result
is used for the cardinality limits. As only these chunks are loaded, I
think we should be good just checking the cardinality limits here.~

EDIT: Documented the logic behind cardinality limits.

Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>

### CODE REVIEW

**Comment by bboreham** [comment]
I think you've missed the intent.

Suppose we have three matchers A, B and C, that gave 1,000,000, 10 and 2 matches.
We want to find A in the cache, skip doing A at all, then intersect B and C.

**Comment by gouthamve** [comment]
So yes, I did miss the intent :) I'll add comments instead.

**Comment by bboreham** [comment]
Seems fair enough, lgtm.  Probably better to get approval from @tomwilkie who wrote the code.

**Comment by tomwilkie** [comment]
:+1:

**Pull request merged**
