### PR TITLE
Fix missing return after writing sharding error

### PR DESCRIPTION
**Pull request by nickbp**
**What this PR does**:
At the moment the error ends up getting overwritten/obscured by the `This should not happen` error handling a few lines further down. This ensures that the original error isn't stomped on.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by pracucci — APPROVED** [review]
Thanks a lot!

_Out of curiosity: how did you spot it? This code is part of a feature still under development which doesn't work out of the box yet._

**Review by pstibrany — APPROVED** [review]

**Comment by spahl** [comment]
I'll answer since Nick is sleeping ;-)

We were working on integrating the alertmanager and ruler in Opstrace (https://github.com/opstrace/opstrace/issues/430) the thread is rather long and show us stumbling around haha:-)

We are working on cortex master and would rather use and test what comes out there since we are not in a rush.

**Comment by pracucci** [comment]
Fantastic!

> We are working on cortex master and would rather use and test what comes out there since we are not in a rush.

Just keep in mind the alertmanager sharding is not ready yet. There are still missing pieces we're working on. Since the work is huge, we're splitting it up in many PRs which get progressively merged to `master`.

**Comment by spahl** [comment]
yeah we disabled it:-) Thanks!

**Pull request merged**
