### PR TITLE
fix potential resolver error in production

### PR DESCRIPTION
**Pull request by sstoner**
**What this PR does**:
the specified resolver is a potential error  
```
2021/05/31 07:08:50 [error] 20#20: *17204171 could not be resolved (110: Operation timed out), client: 192.168.2.24, server: , request: "GET /ruler/rules HTTP/1.1"
```

**Which issue(s) this PR fixes**:

https://github.com/cortexproject/cortex/pull/671#issuecomment-361315828

**Checklist**
- [x] Tests updated
- [x] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by stevesg — COMMENTED** [review]
Thanks for this suggestion, though I don't understand the problem enough to give feedback. My initial feeling is that changing this might work for some people, and break for others.

Could you elaborate on why this change is needed for your environment? (Just for my understanding, thanks!)

**Comment by sstoner** [comment]
> Thanks for this suggestion, though I don't understand the problem enough to give feedback. My initial feeling is that changing this might work for some people, and break for others.

This will not break for others. After removed `resolver`, nginx's DNS requests will be forward to this instance's `resolv.conf`.
 
In contrast, when we set this `resolver`, it may be a misconfiguration for some users for the custom environment and as what [this blog](http://www.devoperandi.com/the-perils-of-a-kube-dns-issue-with-nginx-ingress/) mentioned by [tomwilkie](https://github.com/cortexproject/cortex/pull/671#issuecomment-361315828), we also occur this problem in production.

**Review by pracucci — APPROVED** [review]
LGTM. We shouldn't force to a specific resolver but use the default one. If anyone needs a custom config, then they can override it.

**Review by stevesg — APPROVED** [review]
I liked this part:

> resolving the resolver is well, bad form

**Comment by bboreham** [comment]
The whole `k8s` directory was removed by https://github.com/cortexproject/cortex/pull/4268 so I don't think we need this now.
Maybe there is comparable config in one of the helm charts?

**Pull request closed without merging**
