### PR TITLE
Regex set optimisation when looking series in ingester

### LINKED ISSUE #1993: Optimize for regexp matchers in ingesters
An optimization was made to TSDB's postings/series lookup to reduce query latency in cases where a regex is used for a label matcher. This [change](https://github.com/prometheus/tsdb/pull/602) (and the corresponding [issue](https://github.com/prometheus/prometheus/issues/2651)) should be ported to the ingester chunk lookup code, since the optimization was made to TSDB code and not PromQL.

cc @gouthamve

### PR DESCRIPTION
**Pull request by gouthamve**
Similar to https://github.com/cortexproject/cortex/pull/2446/

Super useful for templated grafana dashboards which send matchers such
as =~"a|b|c|d|e"

Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>

**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #1993 

**Checklist**
- [x] Tests updated
- [x] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by cyriltovena** [comment]
Also closes #1993

**Comment by pstibrany** [comment]
Changelog entry is missing

**Comment by pstibrany** [comment]
> Changelog entry is missing

Perhaps can just extend entry for  #2446, up to you.

**Comment by gouthamve** [comment]
```
➜  cortex git:(regex-opt-ingester) ✗ benchcmp old.txt new.txt
benchcmp is deprecated in favor of benchstat: https://pkg.go.dev/golang.org/x/perf/cmd/benchstat
benchmark                                             old ns/op     new ns/op     delta
BenchmarkSetRegexLookup/select_all-8                  435911065     882075        -99.80%
BenchmarkSetRegexLookup/select_two-8                  247328056     23848         -99.99%
BenchmarkSetRegexLookup/select_half-8                 327012500     530910        -99.84%
BenchmarkSetRegexLookup/select_none-8                 231561666     24398         -99.99%
BenchmarkSetRegexLookup/equality_matcher-8            2474          2488          +0.57%
BenchmarkSetRegexLookup/regex_(non-set)_matcher-8     274129027     276701117     +0.94%
```


Wow! I can't wait to put this in production.

**Pull request merged**
