### PR TITLE
Add shuffle sharding grouper/planner (Clone of PR 4357)

### PR DESCRIPTION
**Pull request by alvinlin123**
This is just a workbench to get https://github.com/cortexproject/cortex/pull/4357 merged. 

Below is a copy from the original PR: 

Signed-off-by: Albert <ac1214@users.noreply.github.com>

**What this PR does**:

Implements generation of parallelize plans for the proposal outlined in https://github.com/cortexproject/cortex/pull/4272 using a shuffle sharding grouper and planner. Currently the parallelizable plans are generated but every compactor runs every planned compaction, the actual sharding will happen in a subsequent PR.

**Checklist**
- [x] Tests updated
- [x] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by alvinlin123** [comment]
Since the original PR was reviewed and approved, I will go ahead and merge.

**Review by roystchiang — APPROVED** [review]

**Review by ShuzZzle — APPROVED** [review]
Test. Should I be able to approve here?! 👀

**Comment by alvinlin123** [comment]
> Test. Should I be able to approve here?! 👀
> 
> Edit: Ah you can but apparently you need write-access. I was worried for a sec, hehe

I was hoping your approval can allow me to merge :-), guess not.

**Comment by alvinlin123** [comment]
Alright, we will use https://github.com/cortexproject/cortex/pull/4624 instead. Closing this one.

**Pull request closed without merging**
