### PR TITLE
RFC: Add integration test for etcd

### LINKED ISSUE #2137: Add integration tests for cassandra, bigtable and etcd

### PR DESCRIPTION
**Pull request by ChinYing-Li**
**What this PR does**:
Adds one integration test for etcd.
Signatures of six functions used in the integration tests had been changed. 
I believe we should also test compactor, store gateway and ruler that use `etcd` as ring backend (hence the signature of `NewRuler`, `NewCompactor` etc. should also be modified), but I'd like to have some early feedback before moving forward.

Questions:
1. Currently, in the backward compatibility tests, only `consul` is used. Shall backward compatibility test cases for `etcd` be added as well?

**Which issue(s) this PR fixes**:
Fixes #2137

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by pstibrany** [comment]
Can you please take a look at failed linter checks? https://github.com/cortexproject/cortex/pull/4113/checks?check_run_id=2431082044

Thank you!

**Comment by ChinYing-Li** [comment]
One irrelevant test is failing; do we need to kick the CI again?

**Comment by ChinYing-Li** [comment]
@pstibrany A gentle ping; A test that seems irrelevant fails. Thanks!

**Comment by pstibrany** [comment]
I don't seem to be able to restart checks here, not sure why. Can you try to push empty commit to your branch instead? That will trigger new run of checks. Thanks!

**Comment by ChinYing-Li** [comment]
The integration test fails in CI probably because I have changed the signature of several `New*` functions in `integration/e2ecortex/service.go`, and those changes are not in the build in the docker image used for CI. I wonder what can I do? Thank you! @pstibrany

**Comment by ChinYing-Li** [comment]
PR ready for review, and any suggestion is appreciated! @pstibrany

**Comment by bboreham** [comment]
Thanks for the PR; sorry it has sat around such a long time.
The "chunks" storage has been deprecated, so this test would be deleted at some point.
Can it be modified to use "blocks" storage?

**Comment by ChinYing-Li** [comment]
Hi, sorry for getting back late; was a bit tied down by the recruiting season. I have introduced the `integration/block_storage_backends_test.go`, which contains one test case.
Any suggestion is appreciated!

**Comment by ChinYing-Li** [comment]
@bboreham Just a ping to let you know I've updated the PR to use block storage. Thank you!

**Review by bboreham — APPROVED** [review]
I might have packaged up `store RingStore, address string` into a struct to reduce the boilerplate at all call-sites, but it's fine as-is.
Thanks!

**Review by alvinlin123 — APPROVED** [review]

**Pull request merged**
