### PR TITLE
Refactor k8s examples to use Cassandra & schema config file

### PR DESCRIPTION
**Pull request by jtlisi**
The purpose of this PR is to simplify the k8s configs for new Cortex users. The schema has been updated to be cloud provider agnostic by using Cassandra as a storage backend. It also utilizes a schema file instead of the flag based schema configuration. Schema files in general are much easier to understand and debug in comparison to flags in my opinion. 

I have refactored this PR to do the following:

- Remove legacy schema definitions from k8s examples
- Remove cloud provider specific storage in favor of Cassandra
- Remove storage flags in favor of a schema config file

Related to #1783 

Signed-off-by: Jacob Lisi <jacob.t.lisi@gmail.com>

### CODE REVIEW

**Comment by jtlisi** [comment]
Sorry about that, my editor automatically lint/formats yaml on save. I can re-dent the file manually.

**Comment by bboreham** [comment]
Looking at this again, did you mean to remove:
```
        - -dynamodb.periodic-table.from=2017-01-06
        - -dynamodb.chunk-table.from=2017-04-17	
```

This will (a) put data in S3 and (b) put the index in one big table.
If you did mean the latter, then you can also remove `-dynamodb.periodic-table.prefix`.

**Comment by bboreham** [comment]
> if it's ok with you I can go ahead and format the rest of the k8s yaml files

no objection but please use separate commits for changes which are supposed to be purely cosmetic and changes which are supposed to achieve an effect.

**Comment by jtlisi** [comment]
Closing this in favor of @gouthamve doing a jsonnet generated implementation

**Pull request closed without merging**
