### PR TITLE
Added tool to dump frontend querier memcache values

### PR DESCRIPTION
**Pull request by joe-elliott**
This tool will dump memcached entries given a list of keys.  Steps to grab keys included in readme.md.

Currently it only supports the frontend querier cache, but could easily be extended to include different caches.

### CODE REVIEW

**Comment by joe-elliott** [comment]
- Added support for gap analysis
  - Take the difference between the first two timestamps in the samplestream and report any future consecutive samples whose difference does not equal this expected interval.
  - Ignore any samples below the min gap threshold
- Ignore Key Misses

cli options:
```
./main -mode=gaps -min-gap=30m
```

**Comment by joe-elliott** [comment]
@gouthamve do we want this PR or should i close it?

**Comment by pracucci** [comment]
@joe-elliott I'm personally a bit dubious about integrating this into Cortex. Have you considered creating a dedicated repo and vendor Cortex?

**Comment by joe-elliott** [comment]
@pracucci 
Agreed.  @jtlisi has encouraged me to PR it to https://github.com/grafana/cortex-cli I just haven't gotten around to it.

Closing.

**Pull request closed without merging**
