### PR TITLE
Compile code in vendor dir; don't download modules again

### LINKED ISSUE #1710: Cortex is not using vendored dependencies in CI
During builds Cortex is not using its vendored dependencies.  This probably changed in the migration to 1.13 due to changes in the way it handled go modules:

https://github.com/golang/go/wiki/Modules#recent-changes

> GO111MODULE=auto enables module-mode if any go.mod is found, even inside GOPATH. 

Example circleci output from a recent PR:
```
CGO_ENABLED=0 go build -ldflags "-extldflags \"-static\" -s -w" -tags netgo -o cmd/cortex/cortex ./cmd/cortex
go: downloading gopkg.in/yaml.v2 v2.2.2
go: downloading github.com/julienschmidt/httprouter v1.2.0
go: downloading github.com/jonboulle/clockwork v0.1.0
go: downloading github.com/mwitkow/go-conntrack v0.0.0-20190716064945-2f068394615f
go: downloading github.com/hashicorp/consul/api v1.1.0
```

### LINKED ISSUE #1795: metadataInIndex flag is broken
Since @tomwilkie asked about this from the stage in PromCon...

As noted in #873:

> The big casualty here is removing the support for metadataInIndex chunks 

So we cannot read data written in 2016.

Given `Chunk.metadataInIndex` is never set we could remove all mention of it from the code.

### PR DESCRIPTION
**Pull request by bboreham**
**What this PR does**:
Tells Go to use the code we have checked in under `vendor`.

**Which issue(s) this PR fixes**:
Fixes #1710 
Fixes #1795

**Checklist**
N/A

### CODE REVIEW

**Comment by bboreham** [comment]
Doesn't seem to work at CircleCI:

```
#!/bin/bash -eo pipefail
CASSANDRA_TEST_ADDRESSES=localhost:9042 make BUILD_IN_CONTAINER=false test
protoc -I /go/src:./vendor:./pkg/querier/frontend --gogoslick_out=plugins=grpc,Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,:./pkg/querier/frontend ./pkg/querier/frontend/frontend.proto
protoc -I /go/src:./vendor:./pkg/querier/queryrange --gogoslick_out=plugins=grpc,Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,:./pkg/querier/queryrange ./pkg/querier/queryrange/queryrange.proto
protoc -I /go/src:./vendor:./pkg/ingester --gogoslick_out=plugins=grpc,Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,:./pkg/ingester ./pkg/ingester/wal.proto
protoc -I /go/src:./vendor:./pkg/ingester/client --gogoslick_out=plugins=grpc,Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,:./pkg/ingester/client ./pkg/ingester/client/cortex.proto
protoc -I /go/src:./vendor:./pkg/ruler/rules --gogoslick_out=plugins=grpc,Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,:./pkg/ruler/rules ./pkg/ruler/rules/rules.proto
./tools/test -netgo
go: downloading github.com/go-kit/kit v0.9.0
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/prometheus/client_golang v1.5.0
go: downloading github.com/weaveworks/common v0.0.0-20200310113808-2708ba4e60a4
go: downloading github.com/prometheus/common v0.9.1
go: downloading github.com/prometheus/prometheus v1.8.2-0.20200213233353-b90be6f32a33
go: downloading github.com/segmentio/fasthash v0.0.0-20180216231524-a72b379d632e
...
```

**Comment by pstibrany** [comment]
This is how Go 1.14 will work out of the box, once we switch to it.

**Comment by bboreham** [comment]
Maybe I should just do Go 1.14 instead.

**Comment by bboreham** [comment]
Probably replaced by #2480

**Comment by pracucci** [comment]
> Probably replaced by #2480

I don't think so. It's a step forward, but doesn't closes this. In order to get what we want we need `go.mod` to switch to `1.14`, according to https://golang.org/doc/go1.14#go-command.

**Comment by pracucci** [comment]
Switching to `1.14` in https://github.com/cortexproject/cortex/pull/2749.

**Comment by pracucci** [comment]
@bboreham I hope you don't mind if I close this PR. We already switched to Go 1.14.

**Pull request closed without merging**
