### PR TITLE
Upgrade Go to 1.17.5 for integration tests + Dockerfiles

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does**:
Upgrade Go to 1.17.5 for integration tests and Dockerfiles.

**Which issue(s) this PR fixes**:

**Checklist**
- [na] Tests updated
- [na] Documentation added
- [na] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by pstibrany** [comment]
Needed for https://github.com/cortexproject/cortex/pull/4601.

**Review by pstibrany — APPROVED** [review]

**Comment by bboreham** [comment]
Why just integration tests?  I would think everywhere this repo specifies a Go version should update at the same time.

**Comment by aknuds1** [comment]
> Why just integration tests? I would think everywhere this repo specifies a Go version should update at the same time.

@bboreham I've updated in the Dockerfiles, which is where I could find a specific Go version otherwise, except for the build image itself (tagged as `20210713_update-go-1.16.6-178ab0c4f`). Is this enough?

**Review by bboreham — APPROVED** [review]
Approved: let's get this merged then update the build image per https://cortexmetrics.io/docs/contributing/how-to-update-the-build-image/

**Comment by aknuds1** [comment]
I think the tests need re-running since ci/test flaked again.

**Pull request merged**
