### PR TITLE
add log to identify request cache hit and cache miss

### PR DESCRIPTION
**Pull request by mengmengy**
Signed-off-by: Mengmeng Yang <mengmengyang616@gmail.com>

**What this PR does**:
Add few more logs to cache results file so that it's easier to figure out a request is skipped cache, cache hit, cache miss when a request split to multiple ones.

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by alanprot** [comment]
We dont have metrics for it already?

**Comment by mengmengy** [comment]
> We dont have metrics for it already?

I think it logs few counters like cortex_cache_hits, cortex_cache_fetched_keys (like below), but from these, we cannot tell which split request got cache hit or cache miss. Please advise if I missed anything.

// TYPE cortex_cache_fetched_keys counter
cortex_cache_fetched_keys{name="frontend.redis"} 3

// TYPE cortex_cache_hits counter
cortex_cache_hits{name="frontend.redis"} 1

**Comment by alvinlin123** [comment]
I am not sure if we should do info logging on the call path that may be high TPS. May have impact on latency.

**Comment by mengmengy** [comment]
> I am not sure if we should do info logging on the call path that may be high TPS. May have impact on latency.

Understood, not all logs will be executed for each split request, for each split request, only 1 log is added. Add such log will be useful when we try to figure out issues like why request is being slow etc. Or do you suggest other better ways we can figure out this I'm not aware?

**Comment by alvinlin123** [comment]
Maybe have it to be debug log instead of info, or maybe like @alanprot suggested, use metrics instead of logs.

**Comment by mengmengy** [comment]
> Maybe have it to be debug log instead of info, or maybe like @alanprot suggested, use metrics instead of logs.

Metrics may not suitable for this case since it will be good to know which split request get cache hit/miss... I updated log level from info to debug.

**Comment by mengmengy** [comment]
@alanprot  @alvinlin123 could you please take a review about the updated PR? Thanks

**Review by alvinlin123 — APPROVED** [review]

**Review by alanprot — APPROVED** [review]

**Pull request merged**
